- README.md
설명과 예시가 달라 헷갈리는 부분이 있어서 모든 커밋 메세지에 문제 이름을 추가하는 것으로 통일시켰습니다 ~!
> docs: commit message에 문제 이름 추가

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
[문제 링크](https://www.acmicpc.net/problem/20061)
1. 파란색 보드, 초록색 보드를 같은 모양으로 만들어서 생각했습니다. (6행 4열 보드판)
2. `t, x, y`를 입력받으면 다음과 같은 3가지 로직을 진행합니다.
1.  블록을 아래로 내립니다.
2.  한 줄이 블록으로 채워졌을 때, 점수를 추가하고 해당 줄을 지워줍니다.
3.  0, 1번째 줄에 블록이 존재할 때, 맨 아래의 줄을 지워주면서 0, 1번째가 모두 비어있을 수 있도록 만들어줍니다.
3. 파란색 보드의 경우 6행 4열로 만들어줬을 때 열을 나타내는 좌표도 수정을 해줘야하지만 좌우 반전된 상태로 진행해도 결과 값에는 영향이 없기 때문에 이대로 진행했습니다.
- 시간복잡도 : O(N^2)
```python
def game():
global blue, green, score
t, x, y = map(int, input().split())
def go_block(t, y, board):
_x = -1
if t == 1:
while _x+1 < 6 and board[_x+1][y] == 0:
_x += 1
elif t == 2:
while _x+1 < 6 and board[_x+1][y] == 0 and board[_x+1][y+1] == 0:
_x += 1
board[_x][y+1] = 1
elif t == 3:
while _x+2 < 6 and board[_x+1][y] == 0 and board[_x+2][y] == 0:
_x += 1
board[_x+1][y] = 1
board[_x][y] = 1
return …
```
> myoung BOJ 20061 모노미노도미노2

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
- myoung/64061/README.md
- myoung/64061/programmers_64061.py
1. 처음에 주어진 board를 순회하여 열마다 인형의 높이가 얼마인지 확인합니다. 그리고 해당 값을 담아줍니다.
2. moves를 하나씩 확인하면서 
1. 해당 숫자 열에 인형이 존재한다면  
2. 인형을 뽑고 bucket에 담습니다.
1. 담기 전, bucket의 맨 위에 담긴 값 (-1인덱스)이 현재 인형과 동일한지 확인하고, 
2. 동일할 경우 bucket에 담지 않고, 기존의 맨 위 값도 pop해주고, 점수를 +2해줍니다.
3. 그리고 해당 열의 높이를 하나 낮춰줍니다.
- 시간복잡도: O(N^2) : 처음에 scan_board에서 2차 배열을 순회합니다요 중간에 break가 있긴 하지만 끝까지 가는 경우가 있을 수 있으므로 O(N^2)이라고 생각했습니다.
```python
def solution(board, moves):
answer = 0
bucket = []
def scan_board(_board):
item_idx = dict()
for _x in range(len(_board)):
find_idx = False
for _y in range(len(_board[_x])):
if _board[_y][_x] > 0:
find_idx = True
item_idx[_x] = _y
break
if find_idx:
continue
if y == len(_board[_x]) - 1 and not find_idx:
item_idx[_y] = -1
return item_idx …
```
> myoung programmers 64061 크레인 인형뽑기 게임

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
- myoung/64061/README.md
- myoung/64061/programmers_64061.py
- myoung/64062/README.md
- myoung/64062/programmers_64062.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64062)
1. 이분탐색을 사용합니다.
1. 처음 left값은 1, right값은 디딤돌에 적힌 숫자 중 최댓 값인 200000000입니다.
2. left와 right의 중간 값인 middle값을 구해줍니다.
3. middle값이 인원이라고 생각하고 디딤돌을 각각 middle로 빼줍니다
4. 만약 `디딤돌 - middle`이 음수인 값이 k개 이상이라면, 구하고자 하는 답이 왼쪽에 존재하므로 right를 middle-1값으로 바꾸어 다시 middle을 구해줍니다.
- 시간복잡도: O(nlogm) n은 디딤돌의 갯수, m은 디딤돌에 적힌 숫자의 최댓값
```python
def solution(stones, k):
left, right = 1, 200000000
while left <= right:
mid = (left + right) // 2
tmp = stones[:]
for i in range(len(tmp)):
tmp[i] -= mid
cnt = 0
is_answer = False
for i in range(len(tmp)):
if tmp[i] <= 0:
cnt += 1
else:
cnt = 0
if cnt >= k:
is_answer = True
break
if is_answer:
right = mid - 1
else:
left = mid + 1
return left
print(solution([2, 4, 5, 3, 2, 1, 4, 2, 5, 1], 3))
```
- 처음에 디딤돌의 최댓값이 …
> myoung programmers 64062 징검다리 건너기

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
- myoung/64061/README.md
- myoung/64061/programmers_64061.py
- myoung/64062/README.md
- myoung/64062/programmers_64062.py
- myoung/64063/README.md
- myoung/64063/programmers_64063.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64063)
1. 방이 있으면 해당 방을 넣고, 방이 없다면 find함수를 사용해 방을 찾습니다. 이 때, reserved_rooms도 갱신해줍니다.
갱신할 때 재귀 호출시마다 모두 remain_room으로 갱신되기 때문에 이 부분에서 시간을 효율적으로 쓸 수 있어서 효율성 통과를 한 것 같슴다.
- 시간복잡도: O(a(N)) , a(N)은 아커만 함수를 의미한다고 합니다. 
- 아커만 함수에서 N이 2^65536일 때, 아커만 함수의 값은 5가 되므로 상수의 시간 복잡도를 가진다고 봐도 무방합니다. (출처: https://dheldh77.tistory.com/entry/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EC%9C%A0%EB%8B%88%EC%98%A8%ED%8C%8C%EC%9D%B8%EB%93%9CUnion-Find-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-1)
```python
import sys
sys.setrecursionlimit(10 ** 7)
def solution(k, room_number):
answer = []
reserved_rooms = dict()
def find(room, reserved_rooms):
if room not in reserved_rooms:
reserved_rooms[room] = room + 1
return room
reserved_rooms[room] = find(reserved_rooms[room], …
```
> myoung programmers 64063 호텔 방 배정

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
- myoung/64061/README.md
- myoung/64061/programmers_64061.py
- myoung/64062/README.md
- myoung/64062/programmers_64062.py
- myoung/64063/README.md
- myoung/64063/programmers_64063.py
- myoung/64064/README.md
- myoung/64064/programmers_64064.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64064)
1. 총 user 중 banned_id 갯수에 맞춰 가능한 조합을 모두 뽑아낸다.
2. 조합을 하나씩 확인(check_group)하여 해당 그룹이 유효한지 확인한다.
3. 유효하다면 ok_lst에 담는다. 이 때, list(set())을 위해 list가 아닌 정렬한 문자열로 저장한다.
4. 중복제거해주고 갯수를 구한다.
- 시간복잡도: ㅠㅠ
```python
def solution(user_id, banned_id):
global group_lst, visited
group_lst = []
ok_lst = []
visited = [False] * len(user_id)
def make_group(group, user_id):
global group_lst, visited
if len(group) >= len(banned_id):
group_lst.append(group[:])
return
for i in range(len(user_id)):
if not visited[i]:
visited[i] = True
make_group(group + [user_id[i]], user_id)
visited[i] = False
def check_group(group):
for i in range(len(banned_id)):
if len(banned_id[i]) != len(group[i]):
return False
else:
for j in range(len(group[i])):
if …
```
> myoung programmers 64064 불량 사용자

- README.md
- myoung/20061/README.md
- myoung/20061/boj20061.py
- myoung/64061/README.md
- myoung/64061/programmers_64061.py
- myoung/64062/README.md
- myoung/64062/programmers_64062.py
- myoung/64063/README.md
- myoung/64063/programmers_64063.py
- myoung/64064/programmers_64064.py
- myoung/64065/README.md
- myoung/64065/programmers_64065.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64065)
1. 입력된 문자열을 잘라서 숫자를 담은 리스트 형태로 바꿔줍니다.
2. 숫자의 갯수가 작은 것부터 정렬을 해줍니다.
3. 앞의 요소에 담겨있지 않은 요소가 answer에 들어갈 요소이기 때문에 해당 요소를 찾아 answer에 넣어줍니다.
- 시간복잡도: O(N) 맞나요 ㅠ
```python
def solution(s):
answer = []
s = s[2:-2].split('},{')
s.sort(key=lambda x: len(x))
prev = []
for i in range(len(s)):
now = list(map(int, s[i].split(',')))
val = [x for x in now if x not in prev]
prev = now
answer.append(val[0])
return answer
```
- 다른 사람들의 풀이를 보다가 더 짧게 접근할 수 있는 로직을 찾아 확인해봤습니다.
```python
from collections import Counter
def solution(s):
s = s[2:-2].replace('},{', ',').split(',')
count = Counter(s)
return [int(i[0]) for i in count.most_common()]
```
counter를 사용해서 제일 많이 쓰인 숫자부터 차곡차곡 answer에 담아줍니다.
- 문자열을 어떻게 더 빠르게 자를 수 있을 까 찾아보았습니다. …
> myoung programmers 64065 튜플

- jonghui/programers_64065/README.md.md
- jonghui/programers_64065/programers_64065.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64065)
1. 슬라이싱과 split을 이용하여 문자를 제거했습니다.
2. ''과 , 만 남는데 빼기를 하기위해 set으로 담았습니다.
3. 리스트에 숫자 갯수에 따라 정리하고 빼기하여 순서대로 담았습니다.
- 시간복잡도: 최대 1000000 (+ 500 + 500)
```python
def solution(s):
answer = []
tuples = list(map(str, s[2:-2].split('},{')))
N = len(tuples)
temp = [{} for _ in range(N)]
for t in tuples:
toint = set(map(int, t.split(',')))
temp[len(toint)-1] = toint
answer += list(temp[0])
for n in range(N-1):
answer += list(temp[n+1]-temp[n])
return answer
```
- 차집합을 하기 위해 리스트로 구현하려고 했으나 set을 이용하여 해결했습니다.
> Jonghui programmers 64065 튜플

- jonghui/programers_64061/README.md.md
- jonghui/programers_64061/programers_64061.py
1. moves를 하나씩 확인하면서
1. 해당 열에 인형이 존재하고
2. basket이 비어있지 않고, 가장 위에 담긴 인형과 같은 인형이면 2점 획득
3. basket이 비어있으면 인형을 담기
- 시간복잡도: 최대 30x1000
```python
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]
moves = [1,5,3,5,1,2,1,4]
def solution(board, moves):
answer = 0
basket = []
for move in moves:
for line in board:
if line[move-1] != 0:
if len(basket) and basket[-1] == line[move-1]:
line[move-1] = 0
basket.pop()
answer += 2
else:
basket.append(line[move-1])
line[move-1] = 0
break
return answer
solution(board, moves)
```
- 주어진 제한사항이 적어서 효율 생각 안하고 풀었습니다
> Jonghui programmers 64061 크레인 인형뽑기

- Park-Dasol/64061/README.md
- Park-Dasol/64061/programmers64061.py
1. 주어진 **board**의 높이를 구해서 **height**에 그 높이를 저장한다.
2. 반복문을 돌면서 **moves**의 이동에 따라 각 칸의 가장 높은 값을 **temp**에 저장한다.
2-1. 이동한 칸의 높이가 board의 전체 길이보다 작을 때(인형이 존재할 때) 인형을 뽑는다. 인형을 뽑았다면, 그 칸의 **height** 값을 변경하고 뽑은 인형을 **board**에서 지운다.
2-2. 그 외(인형이 없을 때)에는 무시한다.
3. 뽑은 인형을 **s**라는 변수에 저장한다.
3-1. s가 비어있거나, s가 비어있지 않으면서 마지막 인형이 뽑은 인형과 다르다면, 뽑은 인형을 추가한다.
3-2. s가 비어있지 않고 마지막 인형이 뽑은 인형과 같다면, 마지막 인형을 없앤다.
4. 3-3의 경우 **answer**에 2를 더한다.
- 시간복잡도
```python
def solution(board, moves):
answer = 0
N = len(board)
height = [0] *N
for j in range(N):
for i in range(N):
if board[i][j] != 0:
height[j] = i
break
s = []
for m in moves:
move = m -1
if height[move] < N:
temp = board[height[move]][move]
if len(s) and s[-1] == temp:
s.pop(-1)
answer += 2
else …
```
> Park-Dasol Programmers 64061 크레인 인형 뽑기

- Park-Dasol/64061/README.md
- Park-Dasol/64061/programmers64061.py
- Park-Dasol/64065/README.md
- Park-Dasol/64065/programmers64065.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64065)
1. 각 문자를 반복문을 돌면서 숫자인지 확인한다. 숫자를 num이라는 변수에 임시 저장한다.
1-1. 숫자일경우, 다음의 문자도 숫자일 경우에 **num**에 저장된 값에 10을 곱하고 숫자를 더한다.(자리수를 만들기 위함)
1-2. 다음 문자가 `,`라면, temp라는 리스트에 지금까지 구한 숫자를 더한다.
1-3. 다음문자가 `}`라면, temp라는 리스트에 지그까지 구한 숫자를 더한뒤, **myList**라는 변수에 **temp**리스트를 더한다. 
2. **myList**를 길이로 정렬한다.
3. myList의 원소와 구한 answer 값을 비교하며 answer을 하나씩 추가한다.
3-1. myList의 길이가 항상 answer보다 1크므로, answer과 myList의 원소를 비교해 같은 원소를 myList에서 제거한다.
3-2. 반복문을 모두 돌 때까지 남아있는 원소를 myList에 추가한다.
- 시간복잡도
```python
def solution(s):
answer = []
temp = []
myList = []
num = 0
for i in range(len(s)):
if s[i].isdigit():
if s[i+1] == '}':
temp.append((num * 10) + int(s[i]))
num = 0
myList.append(temp)
temp = []
elif s[i+1] == ',':
temp.append((num*10) + int(s[i]))
num = 0 …
```
> Park-Dasol Programmers 64065 튜플

- seunghwan/programmers/67256/P67256키패드누르기.java
- seunghwan/programmers/67256/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67256﻿)
왼손 오른손 두 손가락으로 숫자를 누를 때 어떤 손으로 누를지 순서를 출력하는 문제
기본적인 구현 문제로 좌표의 개념만 있다면 쉽게 해결이 가능하다.
왼손과 오른손의 좌표를 계속해서 저장해두고
비교가 필요할 경우
|x1-x2| + |y1-y2| 를 했을 때 더 가까운 손으로
거리가 같으면 왼손잡이 인지 오른손 잡이 인지로 판단하여
누르는 손을 결정하면 된다.
- 시간복잡도
O(n) 
```java
import java.awt.Point;
public class P67256키패드누르기 {
public String solution(int[] numbers, String hand) {
String answer = "";
Point left = new Point(3, 0);
Point right = new Point(3, 2);
Point numPoint[] = new Point[11];
boolean isLeft = false;
if (hand.equals("left")) {
isLeft = true;
}
for (int i = 0; i < 3; i++)
for (int j = 0; j < 3; j++)
numPoint[i * 3 + j + 1] = new Point(i, j);
numPoint[0] = new Point(3, 1);
for (int i : numbers) {
Point target = numPoint[i];
if (i == 1 || i == 4 || i == 7) { …
```
> ysh programmers 67256 키패드 누르기

- myoung/programmers/67256/README.md
- myoung/programmers/67256/programmers_67256.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67256)
1. 키패드를 오른쪽, 왼쪽으로 나눠서 각각의 숫자를 key로 높이를 value로 해서 dict를 하나 만들어줍니다.
2. 현재 왼손 위치, 오른손 위치 정보를 가지고 있는 변수를 만들어줍니다.
3. 주어진 숫자를 하나씩 누르면서, 
왼쪽 열이라면 왼쪽 손가락의 위치 정보를 갱신하고
오른쪽 열이라면 오른쪽 손가락의 위치 정보를 갱신하고
가운데 열이라면 현재 손가락들의 위치와 비교하여 dist가 더 짧은 손가락의 위치정보를 갱신합니다.
- 시간복잡도 : O(N)
```python
def solution(numbers, hand):
left_pos, right_pos = [0, 3], [2, 3]
left_lst = {
1: 0,
4: 1,
7: 2
}
right_lst = {
3: 0,
6: 1,
9: 2
}
center_lst = {
2: 0,
5: 1,
8: 2,
0: 3
}
answer = ''
for num in numbers:
if num in left_lst:
left_pos = [0, left_lst[num]]
answer += 'L'
elif num in right_lst:
right_pos = [2, right_lst[num]]
answer += 'R'
else:
goal = [1, center_lst[num]]
_left = abs(left_pos[0] - goal[0]) + abs(left_pos[1] - goal[1])
_right = abs(right_pos[0] - …
```
> myoung programmers 67256 키패드 누르기

- myoung/programmers/67256/README.md
- myoung/programmers/67256/programmers_67256.py
- myoung/programmers/67257/README.md
- myoung/programmers/67257/programmers_67257.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67257)
1. 입력되는 expression의 형태가 문자열이기 때문에 이를 배열로 바꿔줘야합니다.
사실 입력되는 연산자의 종류가 최대 3개 밖에 되지 않고 문자열 길이도 최대 100이기 때문에
split을 3번만 해줘도 되지만,
정규 표현식을 써보고 싶어서 정규 표현식으로 만들어보았습니다.
[연산자 우선순위 정하기]
1. 순열을 사용해서 나올 수 있는 모든 경우의 수를 계산합니다. (최대 6개이므로)
2. 각각의 우선순위에 따라 연산을 합니다.
[연산]
1. 연산자 배열 1개와 숫자 배열 1개를 만들어줍니다. 
- 중위 표기법으로 표현된 연산식이므로 연산자 배열과 숫자 배열로 만들어줄 경우, 연산자 인덱스 i는 숫자[i]와 숫자[i+1]의 연산을 나타내는 것이기 때문입니다.
2. 같은 연산자인 경우 앞에 있는 것이 우선 순위가 높기 때문에 앞에서부터 순회해줘야합니다.
- 시간복잡도 : 빅오로 나타내는 건 확실치 않아서 숫자로 계산해보겠습니다 ^-^
- 순열에서 나올 수 있는 최대 값: 6
- 각각의 순열에서 나올 수 있는 최대 값: 33 (연산자 최대 갯수)
-> 198
```python
import re
def make_orders(goal, val):
global order_lst, total_orders
if len(val) == goal:
order_lst.append(val)
return
for i in range(goal):
if total_orders[i] not in val: …
```
> myoung programmers 67257 수식 최대화

- seunghwan/programmers/67256/P67256키패드누르기.java
- seunghwan/programmers/67256/README.md
- seunghwan/programmers/67257/P67257수식최대화.java
- seunghwan/programmers/67257/README.md
- seunghwan/programmers/67259/P67259경주로건설.java
- seunghwan/programmers/67259/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67259)
처음엔 pq를 활용해서 현재까지 값이 가장 싼 도로부터 만들어 가장 먼저 도착지에서 나오는 도로의 값을 결과로 나오게 했는데 몇 개의 테케에서 시간초과가 나왔다.
최초 도착지에 도착한 뒤 그 값보다 비싸지는 모든 분기는 고려가 안 되는 것인데 내 예상보다 시간이 더 걸렸나보다.
그래서 풀이방법은
각 자리의 최솟값을 저장해 가며
최솟값이 되게 하는 경로로만 가도록 가지치기 하여
bfs로 모든 경로를 탐색하는 것이다.
- 시간복잡도
O(n^2) 
```java
public class P67259경주로건설 {
class node {
int x;
int y;
int cost;
int d;
public node(int x, int y, int cost, int d) {
super();
this.x = x;
this.y = y;
this.cost = cost;
this.d = d;
}
}
public int solution(int[][] board) {
Queue<node> q = new LinkedList<node>();
int[][] costs = new int[board.length][board.length];
for (int i = 0; i < costs.length; i++)
Arrays.fill(costs[i], Integer.MAX_VALUE); …
```
> ysh programmers 67259 경주로 건설

- seunghwan/programmers/67256/P67256키패드누르기.java
- seunghwan/programmers/67256/README.md
- seunghwan/programmers/67257/P67257수식최대화.java
- seunghwan/programmers/67257/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67257)
우선 입력으로 주어진 식을 수와 연산자로 분리하여
따로 배열에 저장한다.
이후 + - * 의 우선순위를 정해야하므로
3가지 원소의 순열을 구한다.
순열로 정해진 순서에 따라
연산자 배열에서 해당 연산자를 찾아 꺼낸 뒤
연산자에 해당하는 숫자를 꺼내 계산하고 다시 집어넣는다.
이 개념으로 3가지 연산자를 모두 계산하면 해결이 가능하다.
주의) 결과 값이 크니 long을 사용해야 한다.
- 시간복잡도
O(n)  3! * n
```java
public class P67257수식최대화 {
static ArrayList<Long> numlist = new ArrayList<Long>();
static ArrayList<Character> opList = new ArrayList<Character>();
static char[] choice = new char[3];
static boolean[] visit = new boolean[3];
static char[] booho = { '+', '-', '*' };
static long max = Long.MIN_VALUE;
public long solution(String expression) {
String s = "";
for (char a : expression.toCharArray()) {
if (a == '-' || a == '+' || a == '*') { …
```
> ysh programmers 67257 수식최대화

- myoung/programmers/67256/README.md
- myoung/programmers/67256/programmers_67256.py
- myoung/programmers/67257/README.md
- myoung/programmers/67257/programmers_67257.py
- myoung/programmers/67258/README.md
- myoung/programmers/67258/programmers_67258.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67258)
0. 투포인터를 이용해서 풀이를 진행했습니다.
1. 오른쪽으로 가다가 visited의 key 값이 모든 종류의 보석이 되었을 때, 
left를 오른쪽으로 움직이면서 범위를 줄여나갑니다.
- 시간복잡도 : O(N) 
- 투포인터의 시간 복잡도는 O(N)입니다.
```python
def solution(gems):
answer = []
visited = {}
type_nums = len(set(gems))
min_dist = len(gems)+1
_left, _right = 0, 0
while _right < len(gems):
if gems[_right] in visited:
visited[gems[_right]] += 1
else:
visited[gems[_right]] = 1
_right += 1
if len(visited) == type_nums:
while _left < _right:
if visited[gems[_left]] > 1:
visited[gems[_left]] -= 1
_left += 1
elif min_dist > _right - _left:
min_dist = _right - _left
answer = [_left + 1, _right]
break
else:
break
return answer
```
- 처음에는 슬라이딩 윈도우로 접근했다가 엄청난 `시간초과`를 맞이했습니다.
그래서 투포인터로 바꿔서 접근을 했습니다.
- 딕셔너리 데이터 삽입 및 삭제 …
> myoung programmers 67258 보석 쇼핑

- myoung/programmers/67256/README.md
- myoung/programmers/67256/programmers_67256.py
- myoung/programmers/67257/README.md
- myoung/programmers/67257/programmers_67257.py
- myoung/programmers/67258/README.md
- myoung/programmers/67258/programmers_67258.py
- myoung/programmers/67259/README.md
- myoung/programmers/67259/programmers_67259.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67258)
0. BFS사용
1. 시작 지점: (0, 0), 도착 지점: (N-1, N-1)
2. 갈 수 있는 방향 : 상, 하, 좌, 우 -> 4가지 존재
3. 현재 지점에서 갈 수 있는 방향으로 움직여보고(tx, ty)
1. 만약 tx, ty가 범위를 벗어나거나, 1이 들어있으면 queue에 담지 않는다.
2. 만약 `board[ty][tx]`값이 0이라면
1. 현재 방향과 tx, ty의 방향이 동일한 경우, 
- `현재 money + 100`을 `board[ty][tx]`에 담고, queue에 담는다.
2. 현재 방향과 tx, ty의 방향이 다른 경우,
- `현재 money + 600`을 `board[ty][tx]`에 담고, queue에 담는다.
- money+600 인 이유는, 코너(500) + 직선(100) 이므로
3. 만약 `board[ty][tx]`값에 1, 0이 아닌 `money` 값이 들어 있다면 (이미 방문한 적이 있는 경우)
1. 예상되는 money (`현재 money + 100`or `현재 money + 600`)와 `board[ty][tx]`에 담겨있는 `money` 값 비교
1. 만약 기존에 담겨있는 값보다 예상되는 money 값이 더 작거나 같은 경우 -> tx, ty를 queue에 담음
- 시간복잡도 : O(N^2) 
- 탐색을 통해 거의 맵 전체를 확인하기 때문에 O(N^2)입니다ㅏ욧
```python
from collections import deque
def …
```
> myoung programmers 67259 경주로 건설

- seunghwan/programmers/17676/P17676추석트래픽.java
- seunghwan/programmers/17676/README.md
- seunghwan/programmers/17679/P17679프렌즈4블록.java
- seunghwan/programmers/17679/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17679)
애니팡같은 문제
순수 구현문제라 주어진 요구조건에만 맞추면 풀이가 가능하다.
\1. 먼저 블록 중 2*2 모양의 블록을 모두 찾고
\2. 찾은 블록들을 빈칸으로 비운다.
\3. 그 빈칸 위의 칸들을 모두 밑으로 내려준다.
이것을 2*2모양의 블록이 찾아지지 않을 때까지 반복하고
없어진 블록의 갯수를 출력한다.
끝
- 시간복잡도
O(n^2)
```java
class P17679프렌즈4블록 {
public int solution(int m, int n, String[] board) {
char[][] map = new char[m][n];
for (int i = 0; i < m; ++i)
map[i] = board[i].toCharArray();
while (true) {
int cnt = checkBlock(m, n, map);
if (cnt == 0)
break;
answer += cnt;
dropBlock(m, n, map);
}
return answer;
}
private void dropBlock(int m, int n, char[][] map) {
for (int i = m - 1; i >= 0; i--)
for (int j = 0; j < n; j++) {
if (map[i][j] != '.')
continue;
for (int row = i - 1; row >= 0; row--) {
if (map[row][j] != '.') {
map[i][j] = …
```
> ysh programmers 17679 프렌즈4블록

- seunghwan/programmers/67256/P67256키패드누르기.java
- seunghwan/programmers/67256/README.md
- seunghwan/programmers/67257/P67257수식최대화.java
- seunghwan/programmers/67257/README.md
- seunghwan/programmers/67259/P67259경주로건설.java
- seunghwan/programmers/67259/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67260)
트리구조에서 모든 정점을 들려야하는데
조건으로 정점 간에 선행관계가 있을 때 이 트리의 모든 정점을 지날 수 있는지 구하는 문제
기본 목표는 모든 정점을 도는 것이므로 bfs를 활용하여 풀이하였다.
0번부터 시작하여 bfs를 돌아가는데
정점에 들어 갈 때 3가지 경우가 있다.
1. 선행 정점이 없는 경우
2. 선행 정점이 이미 방문된 경우
3. 선행 정점이 아직 방문되지 않은 경우
1번과 2번 경우는 해당 정점을 방문하는데 결격사유가 없으므로 바로 방문을 하면 되고
3번의 경우가 특수한데
해당 정점에 도달은 성공하였지만 선행정점이 아직 방문되지 않은 경우이기 때문에
다르게 보면 선행정점만 방문이 이루어지면 해당정점에도 방문이 가능하다는 소리가 된다.
그렇기 때문에 3번상황이 나오게 되면
이후 선행정점을 방문하게 되면 바로 해당정점을 방문하도록 해주면 된다.
이것을 제외하고는 일반적인 bfs와 같이 풀이하면 된다.
- 시간복잡도
O(n) 
```java
public class P67260동굴탐험 {
public boolean solution(int n, int[][] path, int[][] order) {
boolean answer = true;
ArrayList<ArrayList<Integer>> matList = new …
```
> ysh programmers 67260 동굴탐험

- seunghwan/programmers/17676/P17676추석트래픽.java
- seunghwan/programmers/17676/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17676)
1분이란 시간안에 처리중인 요청의 갯수가 가장 많은 것을 찾는 문제
00:00:00 ~ 23:59:59.999 까지의 범위 안에서 진행된다.
그래서 모든 범위를 ms로 통일 시켜서 진행하였다.
범위는 0 ~ 1000 * 60 * 60 * 24 = 86400000 이다.
그런데 범위를 구하고 보니 O(n)으로 모든 범위를 한번만 본다면 해결이 되겠는데? 싶어
0~ 8640만 안을 슬라이딩 윈도우로 한번만 보도록 구현하였다.
먼저 입력으로 들어온 종료시간을 ms로 바꾸고
처리시간을 빼서 시작시간 역시 구한다.
시작시간을 카운트 해놓는 배열과 종료시간을 카운트 해놓는 배열을 만들고
구한 시작시간과 종료시간에 +1을 해둔다.
이후 슬라이딩 윈도우로 이동하며
시작시간에 걸치면 처리량 +1
종료시간에 걸치면 처리량 -1 을 통해
1분동안의 처리량을 구하고
이 중 최댓값을 구하면 된다.
- 시간복잡도
O(1) (86400000) 
```java
public class P17676추석트래픽 {
//1000*60*60*24 = 86400000
public int solution(String[] lines) {
int startTable[] = new int[24*60*60*1000];
int endTable[] = new int[24*60*60*1000];
for(String time : lines) {
int endTime = 0;
String[] times = time.split(" "); …
```
> ysh programmers 17676 추석트래픽

- seunghwan/programmers/17676/P17676추석트래픽.java
- seunghwan/programmers/17676/README.md
- seunghwan/programmers/17678/P17678셔틀버스.java
- seunghwan/programmers/17678/README.md
- seunghwan/programmers/17679/P17679프렌즈4블록.java
- seunghwan/programmers/17679/README.md
- seunghwan/programmers/17683/P17683방금그곡.java
- seunghwan/programmers/17683/README.md
- seunghwan/programmers/17684/P17684압축.java
- seunghwan/programmers/17684/README.md
- seunghwan/programmers/17687/P17687n진수게임.java
- seunghwan/programmers/17687/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17678)
해결방법을 떠올리는 것보다 문제 이해하는데 시간이 더 걸린 문제.
그림이 있었다면 더 쉽게 이해했을것 같은데
만약 그림이 있었다면 그것만으로도 너무 큰 힌트가 될 수 있을 것 같긴하다.
버스는 9시부터 첫차가 출발하고 t분 간격으로 n번 한번에 최대 m명을 데리고 갈 수 있다.
여기서 콘이 버스를 타는 방법 중 시간이 가장 뒤인 것을 찾으면 된다.
여기서 콘은 같은 시간대에 온 사람들 중 가장 마지막으로 타게 된다는 조건이 있어
첫차를 제외하고는 못타는 경우의 수가 있을 수 있다.
그래서 첫 버스부터 콘이 이 버스를 탄다면 탈 수 있는 시간을 구한 뒤 다음 버스로 넘어가는 식으로 풀이를 진행했다.
먼저 크루의 도착시간이 뒤죽박죽이므로 정렬을 시켜주고
도착시간을 계산하기 편하게 분을 기준으로 수로 변경해준다.
그리고 크루들은 선입선출로 버스를 타고 갈것이니 큐에 저장해주었다.
********
이제 각 버스에 대해서
버스는 우선 한자리를 제외하고 크루들을 모두 태우고
남은 자리에 대해
1. 한자리가 아닌 두자리 이상이 남거나
2. 다음 순번 크루가 어차피 탈 수 없다면 콘은 버스가 도착하는 시간에만 도착해도 탈 수 있다.
3. 다음 순번 크루가 탈 수 있었다면 그 크루보다 순서가 빨라야하므로 1분 일찍 도착하면 탈 수 있다.
이 3가지 경우로 나누어
콘이 버스를 탈 수 있는 경우 시간을 저장해두고
마지막에 HH : MM 형태로 바꾸어 return해주면 된다.
- 시간복잡도
O(n+m) …
> ysh programmers 17678 셔틀버스

- seunghwan/programmers/17676/P17676추석트래픽.java
- seunghwan/programmers/17676/README.md
- seunghwan/programmers/17679/P17679프렌즈4블록.java
- seunghwan/programmers/17679/README.md
- seunghwan/programmers/17683/P17683방금그곡.java
- seunghwan/programmers/17683/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17683)
이 문제 역시 문자열 관리를 잘해주면 된다.
먼저 사용되는 각 문자열중에 C# 과 같이 #이 붙은 친구들은 길이는 2인데 음은 하나이므로
계산시에 불편함이 있다.
그래서 C#과 같은 음들은 소문자로 변경하여 풀이하였다.
사전작업을 마친 뒤 풀이를 진행해 보면
1. 플레이타임 구하기
2. 플레이타임에 맞춰 총 실행된 음들 구하기
3. 네오가 구한 멜로디가 포함되었는지 contains함수로 비교
4. 기존에 찾은 멜로디와 플레이타임 비교하여 정답 저장
5. 끝~
위 순서대로 진행하면 된다.
- 시간복잡도
O(n+m) contains 함수의 문자열 비교 알고리즘.
```java
public class P17683방금그곡 {
public String solution(String m, String[] musicinfos) {
m = changeShap(m);
int time = 0;
String answer = "(None)";
for (String music : musicinfos) {
String[] musicinfo = music.split(",");
int H1 = Integer.parseInt(musicinfo[0].substring(0, 2));
int M1 = Integer.parseInt(musicinfo[0].substring(3, 5));
int H2 = Integer.parseInt(musicinfo[1].substring(0, 2));
int M2 = …
```
> ysh programmers 17683 방금그곡

- seunghwan/programmers/17676/P17676추석트래픽.java
- seunghwan/programmers/17676/README.md
- seunghwan/programmers/17679/P17679프렌즈4블록.java
- seunghwan/programmers/17679/README.md
- seunghwan/programmers/17683/P17683방금그곡.java
- seunghwan/programmers/17683/README.md
- seunghwan/programmers/17684/P17684압축.java
- seunghwan/programmers/17684/README.md
- seunghwan/programmers/67260/P67260동굴탐험.java
- seunghwan/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17684)
LZW 압축방식을 직접 구현해보는 문제
문자열을 자르고 Hash 개념만 안다면 쉽게 해결이 가능하다.
먼저 A ~ Z를 Hash 테이블에 추가하고
문자에서 사전에 등록되지 않은 subString을 찾을 때까지 검사하고
찾으면 직전에 찾았던 사전에 등록된 값을 answer에 저장,
subString을 새롭게 사전에 등록.
이것을 계속해서 반복해주고
마지막 문자열에 도달하면 더이상 찾을 수 없으므로
바로 사전에 등록된 값을 저장하고 마치면 된다.
- 시간복잡도
O(n)
```java
import java.util.HashMap;
public class P17684압축 {
public int[] solution(String msg) {
HashMap<String, Integer> dic = new HashMap<String, Integer>();
ArrayList<Integer> answerList = new ArrayList<Integer>();
for(char i = 'A' ; i <= 'Z'; i++)
dic.put(i+"", i-'A'+1);
int dicNum = 27;
for(int i = 0 ; i < msg.length();i++) {
for(int j = 1 ; i+j<= msg.length() ; j++) {
String target = msg.substring(i, i+j);
if(dic.get(target) == null) { …
```
> ysh programmers 17684 압축

- myoung/programmers/17677/README.md
- myoung/programmers/17677/programmers_17677.py
- myoung/programmers/17680/README.md
- myoung/programmers/17680/programmers_17680.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17680)
0. deque를 사용하여 LRU를 구현합니다.
1. cache에 존재하면 `cache hit`, cache에 존재하지 않을 경우 `cache miss`이기 때문에 실행시간을 각각의 상황에 맞추어 더해줍니다.
2. `cache miss`의 경우 중 cache가 다 찬 경우, 맨 앞의 요소를 하나 빼주고 현재 요소를 맨 뒤에 넣어줍니다.
3. cache에 존재했던 요소의 경우, 해당 요소를 제거하고 맨 뒤에 넣어줍니다. (우선순위 고려)
- 시간복잡도: O(N) 
- N은 cities 요소의 갯수입니다.
```python
from collections import deque
def solution(cacheSize, cities):
answer = 0
cache = deque()
if cacheSize == 0:
return len(cities) * 5
for city in cities:
city = city.lower()
if city in cache:
answer += 1
cache.remove(city)
else:
if len(cache) >= cacheSize:
cache.popleft()
answer += 5
cache.append(city)
return answer
```
- `deque`의 `maxlen`을 사용하면 위의 코드가 더욱 간결해질 수 있습니다.
```python
def solution(cacheSize, cities):
import collections
cache = …
```
> myoung programmers 17680 캐시

- myoung/programmers/17677/README.md
- myoung/programmers/17677/programmers_17677.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17677)
0. "AB"와 "ab"는 같은 문자 취급하기 때문에, `str1`과 `str2`를 모두 소문자로 만들어서 시작했습니다.
1. 각 문자를 2개씩 쪼개서 dict형으로 만들어 `key`: '문자 이름', `value`: '문자가 등장한 갯수'를 넣어줍니다. 
- 이 때, 문자의 형식이 올바르지 않은 경우는 제외해줍니다.
2. 각각의 key값들이 등장한 문자이기 때문에, `set` 메서드를 이용하여 교집합(`&`)과 합집합(`|`)을 만들어줍니다.
3. 교집합 요소의 경우 `str1`, `str2` 중 더 적은 count 값을 가지므로, min값을 분자에 더해줍니다
4. 합집합 요소의 경우 `str1`, `str2` 중 등장한 집합에서의 count값을 가지는데, 이 때 두 집합 모두에서 등장한 경우에는 더 많은 count 값을 가지므로, max값을 분모에 더해줍니다.
5. 분자/분모를 해주는데, 나눗셈이 정의되지 않아(zero에러 등) 계산이 불가할 경우는 문제에 정의된 대로 1값을 가지고, 나머지 경우는 연산을 진행하여 답을 도출합니다.
- 시간복잡도: O(N+M) 
- N은 str1의 길이, M은 str2의 길이입니다.
- 2개씩 쪼개서 모두 확인해야하기 때문에 N개의 문자열을 2개씩 쪼갤 경우 총 (N-1)개가 되어서 O(N+M)이라고 생각했습니다.
```python
import re
def solution(str1, str2):
str1, str2 = str1.lower(), …
```
> myoung programmers 17677 뉴스 클러스터링

- myoung/programmers/17677/README.md
- myoung/programmers/17677/programmers_17677.py
- myoung/programmers/17680/README.md
- myoung/programmers/17680/programmers_17680.py
- myoung/programmers/17681/README.md
- myoung/programmers/17681/programmers_17681.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17681)
0. N의 범위가 1~16이라 완전탐색 문제라고 생각했습니다.
1. 각각의 arr들을 이진수로 변환합니다.
2. 이진수로 변환된 맵을 하나씩 확인하면서 맵 합칩니다.
1. `0`: 공백, `1`: 벽
2. 두가지 맵 중 하나라도 `1`이면 `1`
3. 두가지 맵 모두 `0`이면 `0`
4. `0`인 경우 공백으로 나타내고, `1`인경우 `#`으로 나타내어 출력합니다.
- 시간복잡도: O(N^2) 
```python
def solution(n, arr1, arr2):
def trans_map(arr):
new_arr = []
for i in range(n):
val = ''.join(bin(arr[i]))[2:]
while len(val) < n:
val = '0' + val
new_arr.append(val)
return new_arr
def add_map(map1, map2):
new = []
for y in range(n):
line = ''
for x in range(n):
if map1[y][x] == map2[y][x] and map1[y][x] == '0':
line += ' '
else:
line += '#'
new.append(line)
return new
new1, new2 = trans_map(arr1), trans_map(arr2)
return add_map(new1, new2)
```
저는 n개의 요소를 가진 map형식을 맞춰주기 위해 `while`문을 사용했는데, 다른 …
> myoung programmers 17681 비밀지도

- myoung/programmers/17678/README.md
- myoung/programmers/17678/programmers_17678.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17678)
1. 시간은 모두 분(min)을 기준으로 바꾸어 문제풀이를 진행했습니다.
2. 먼저, 가능한 셔틀 시간을 모두 shuttles리스트에 담아줍니다. (셔틀 운행 횟수, 간격 고려)
3. 크루들이 대기열에 오는 시간을 모두 리스트에 담아주고, 정렬해줍니다.
4. 일단 모든 크루를 셔틀에 태워봅니다.
1. 만차의 기준: 마지막 셔틀 버스가 만차인지 아닌지.
2. 만차라면, 제일 뒷 시간인 사람보다 1분 빠른 시간이 답이 됩니다.
3. 만차가 아닌 경우, 마지막 셔틀 버스 시간이 답이 됩니다. (셔틀 도착 시간까지 탈 수 있으므로)
- 시간복잡도: O(N+M)
- 각 버스에 해당 승객이 탈 수 있는지 없는지 확인해야하므로 O(N+M)입니다. (N = 버스 수, M = 승객 수)
```python
def solution(n, t, m, timetable):
shuttles = [(540 + t * i) for i in range(n)]
def trans_timetable_to_num():
trans_lst = []
for time in timetable:
_hour, _min = map(int, time.split(':'))
trans_lst.append((_hour * 60) + _min)
return trans_lst
def shuttle_info(people, shuttles):
infos = [0] * len(shuttles)
person_idx = 0
for i in …
```
> myoung programmers 17678 셔틀버스

- myoung/programmers/17679/README.md
- myoung/programmers/17679/programmers_17679.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17679)
1. 주어진 board를 모두 순회한다.
이 때, 현재 좌표 (x, y)를 기준으로 오른쪽`(x+1, y)`, 아래`(x, y+1)`, 오른쪽 아래`(x+1, y+1)`가 모두 같은 모양이라면 -> 추후에 지워질 블록이기 때문에 리스트에 `(x, y)`를 담아놓는다.
(바로 지우지 않는 이유 : 겹치는 경우가 존재하므로)
2. 순회 후 지워질 블록 리스트를 하나씩 확인하며 오른쪽, 아래, 오른쪽 아래 블록까지 모두 지운다. 지우면서 이 블록이 겹치는 블록인지 확인하고, 겹치지 않는 블록이라면 count +1, 겹치는 블록인데 이미 지워진 블록이라면 pass한다.
3. 블록을 지운 후 위에 있는 블록이 아래로 떨어져 빈 공간을 채운다.
4. `1-3`의 로직을 지울 수 있는 블록이 존재하지 않을 때까지 반복한다.
- 시간복잡도: O(N*M)이라고 생각했습니다. (순회하므로)
```python
def solution(m, n, board):
answer = 0
dx = [0, 1, 0, 1]
dy = [0, 0, 1, 1]
board = [list(board[i]) for i in range(m)]
def is_board(x, y):
if 0 <= x < n and 0 <= y < m and board[y][x] != 0:
return True
return False
def near_same():
arr = []
for y in range(m):
for x in range(n):
val = …
```
> myoung programmers 17679 프렌즈4블록

- myoung/programmers/17687/README.md
- myoung/programmers/17687/programmers_17687.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17687)
1. 숫자를 n진법으로 바꿀 수 있는 함수가 필요합니다.
2. `게임에 참가하는 인원 * 미리 구할 숫자의 갯수` 크기의 배열을 하나 만들어서 진법으로 나타낸 숫자를 넣어줍니다.
3. 튜브의 순서에 맞춰 말해야하는 숫자를 answer에 담아줍니다.
- 시간복잡도: O(`N*logN`) : N은 m*t 배열에 들어갈 수 있는 최대 숫자(십진법 기준)입니다. logN이 붙은 이유는 n진법으로 나타낼 때 logN으로 나타낼 수 있기 때문입니다.(로그의 밑은 2~16 가능)
```python
def dec2num(d, n):
dct = {
10: 'A',
11: 'B',
12: 'C',
13: 'D',
14: 'E',
15: 'F'
}
_num = ''
if d == 0:
return '0'
while d > 0:
d, _namuji = divmod(d, n)
if _namuji >= 10:
_namuji = dct[_namuji]
else:
_namuji = str(_namuji)
_num = _namuji + _num
return _num
def solution(n, t, m, p):
nums = [None] * (m*t)
val = 0
idx = 0
while not nums[-1]:
now_val = dec2num(val, n)
if idx + len(now_val) >= m*t:
for v in range((m*t)-idx):
nums[idx+v] = now_val[v]
break
for …
```
> myoung programmers 17687 n진수 게임

- seunghwan/programmers/17678/P17678셔틀버스.java
- seunghwan/programmers/17678/README.md
- seunghwan/programmers/17683/P17683방금그곡.java
- seunghwan/programmers/17683/README.md
- seunghwan/programmers/17684/P17684압축.java
- seunghwan/programmers/17684/README.md
- seunghwan/programmers/17685/P17685자동완성bfs.java
- seunghwan/programmers/17685/README.md
- seunghwan/programmers/17686/P17686파일명정렬.java
- seunghwan/programmers/17686/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17686)
문자열 형태의 구현 문제
시키는데로만 구현하면 어려울 것 없는 문제다.
먼저 들어온 파일명에서 숫자를 찾고 그 숫자가 끝나는 지점을 찾는다.
찾은 숫자 이전까지를 head, 숫자가 number가 되도록 저장을 하고
compareTo 함수를 이용해 정렬 방식을 문제에 맞게 세팅해주면 된다.
나는 head와 숫자가 모두 같으면 순번 그대로 유지가 되어야 하므로
확실히 하기위해 order도 같이 저장하여 compare 조건에 넣어 두었다.
주의할 점으로
숫자의 끝지점을 찾을 때 수가아닌 다른 문자가 나오면 그 부분을 끝으로 찾는 식으로 구현하면
수 뒤에 아무것도 없을 경우 Runtime error 가 뜨게 된다.
이 부분에 유의하면서 풀이하도록 하자.
- 시간복잡도
O(NlogN)
```java
import java.util.Collections;
import java.util.List;
public class P17686파일명정렬 {
class file implements Comparable<file>{
String origin;
String head;
int num;
int order;
public file(String origin, String head, int num, int order) {
super();
this.origin = origin;
this.head = head;
this.order = order; …
```
> ysh programmers 17686 파일명정렬

- seunghwan/programmers/17678/P17678셔틀버스.java
- seunghwan/programmers/17678/README.md
- seunghwan/programmers/17683/P17683방금그곡.java
- seunghwan/programmers/17683/README.md
- seunghwan/programmers/17684/P17684압축.java
- seunghwan/programmers/17684/README.md
- seunghwan/programmers/17685/P17685자동완성bfs.java
- seunghwan/programmers/17685/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/17685)
트리와 bfs를 이용해 풀이하였다.
단 트리로 만들 시 go, gone 같은경우
go가 word인지 아닌지 구별할 방법이 없으므로
모든 단어끝에 마지막을 의미하는 E를 붙여주었다.
이렇게 되면
goneE같은경우 n까지만 누르면 E는 자동완성의 한부분이니 신경쓰지 않아도 되고
goE에서만 실제론 go만치면 되지만 E까지 치게 되었으므로 이런 때에만 타이핑횟수 계산후 -1 해주면 된다.
타이핑 횟수 계산은
bfs를 통해 depth와 타이핑 횟수를 저장하며 진행 되고
현재위치에서 가지가 한개라면 depth만 올라가고 타이핑 횟수는 그대로인 상태로 이동
가지가 두개이상이면 타이핑 횟수 = depth로 변경하여 이동하며
E를 만나게 되면 현재까지 타이핑횟수를 answer에 저장하면 된다.
주의
dfs로 풀이할 시 깊이가 최대 100만까지 가능하니 스택이 터지게 되므로
bfs로 풀이하여야 한다.
실패한 dfs코드도 밑에 첨부해 두겠다.
- 시간복잡도
O(L)
```java
import java.util.HashMap;
public class P17685자동완성bfs {
static class node{
HashMap<Character, HashMap> hash;
int nowDepth;
int clickDepth;
public node(HashMap<Character, HashMap> hash, int …
```
> ysh programmers 17685 자동완성

- seunghwan/programmers/60059/P60059자물쇠와열쇠.java
- seunghwan/programmers/60059/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60059)
N이 20 밖에 안되는 매우 작은 크기이다.
그래서 모든 경우의 수를 가지고 모든 경우의 수에 대입해 확인하는 식으로 풀이를 진행하였다.
우선 키의 홈이 이동시킬 수 있고 바깥면으로 이동시켜서 안보이게하는 것도 가능하다.
이것을 다르게 보면
이렇게 키후보가 될수도
이렇게 키후보가 될 수도 있는 것이다.
이것을 쉽게 구현하기 위해
키를 확장시켜서
이렇게 만들고 원래 키의 크기에 맞춰 0,0 부터 서브키를 만들어 모든 경우의수를 확인할 수 있다.
회전의 경우에도 이 상태에서 그대로 회전을 시키고 똑같은 방법으로 서브키를 만들어 확인하면 된다.
이렇게 서브키를 만들었으면
자물쇠에 그대로 갖다 대보며 맞는지 안맞는지 모두 검사하고
맞는 키가 있다면 true
없다면 false를 리턴하면 된다.
경우의 수를 얼추 따져보면
우선 키후보의 수는
최대 4M^2 * 4 정도
뽑은 키후보를 자물쇠에 비교해보는 경우의수 (N-M+1)^2
각 비교마다 M^2
16M^4 * (N-M+1)^2정도 일 것 같다.
최악으로 생각해도
19,360,000 정도로 충분히 완탐으로 풀이가 가능했다.
- 시간복잡도
O(M^4*(N-M+1)^2) 
```java
public class P60059자물쇠와열쇠 {
public boolean solution(int[][] key, int[][] lock) {
int keyLength = key.length;
key = extend(key);
int blank = 0;
for (int i …
```
> ysh programmers 60059 자물쇠와열쇠

- seunghwan/programmers/60063/P60063블록이동하기.java
- seunghwan/programmers/60063/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60063)
풀이 개념 자체는 정말 간단한데
극한의 구현 복잡도를 가진 문제
사실 구현 복잡도도 그렇게 복잡하다 할 편은 아니긴 하지만
뭔가 비효율적으로 조건을 따져봐야만 해서 풀이 내내 답답하게 느껴져서 그렇게 느껴지는 것 같다.
문제 자체는 단순히 bfs를 이용해 도착지 까지 가장 빠른 경로를 찾는 문제인데,
이동 시
4방향 이동과
1번 축 시계,반시계 회전
2번 축 시계,반시계 회전
총 8개의 분기로 나뉘어 들어간다.
4방향 이동은 일반적인 bfs같이 이동을 하면 되는데
문제는 축 회전시
축과 대각선 칸, 회전 후 자리할 위치 칸 두자리를 검사해야 하는데
회전도 가로로 있을때와 세로로 있을때의 검사 위치가 달라진다.
또 이것이 시계방향, 반시계방향으로 나뉘어진다.
여기에도 규칙성이 있기야 하겠지만 규칙성을 찾아 구현한다해도 복잡한 형태로 나올것 같아,
결국 하드 코딩을 하는데 그 양이 어마어마해서
조건을 각각 생각해보며 풀이하는 것이 머리 아팠다.
회전과 관련된 것은 하드코딩 하였으므로 따로 적지는 않도록 하겠다.
이제 bfs를 통해
가장 먼저 도착한 분기에서 시간을 return하면 된다.
- 시간복잡도
O(n^2) 
```java
import java.util.HashSet;
public class P60063블록이동하기 {
class robot{
int x1;
int y1;
int x2;
int y2; …
```
> ysh programmers 60063 블록 이동하기

- seunghwan/programmers/60061/P60061기둥과보설치.java
- seunghwan/programmers/60061/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60061)
이 문제에서 가장 중요한 부분
저 말에 맞춰 설치와 삭제가 가능한지만 판단하면 된다.
먼저 설치시에는
기둥설치는 밑에 바닥,보,기둥 중 하나가 있는지 확인
보 설치는 양옆에 보가 있거나 설치위치 또는 오른쪽 위치 아래에 기둥이 있는지 확인
이렇게만 확인을 하면된다.
삭제시에는 좀더 간단하게
현재 기물을 삭제를 하면 영향을 받는 위치에 무언가 설치되어있다면
우선 현재 기물이 삭제된 뒤에 그 영향을 받는 위치에 다시 설치가 가능한지 검사를 하여
현재 기물 없이도 그 기물이 멀쩡 할 수 있다면 삭제되어도 되는 것이다.
예를 들어 기둥을 삭제하는데
내 위에 기둥이 있다면
그 기둥이 나없이도 설치가 가능한지 미리 만들어둔 설치검사 함수를 실행해 확인해 보는 것이다.
이 부분이 해당 함수 부분이다.
끝
- 시간복잡도
O(n^2) 
```java
public class P60061기둥과보설치 {
int[][] pillar;
int[][] beam;
public int[][] solution(int n, int[][] build_frame) {
pillar = new int[n+1][n+1];
beam = new int[n+1][n+1];
for (int frame[] : build_frame) {
int x = frame[0];
int y = frame[1];
int a = frame[2]; // 0기둥 1프레임
int b = frame[3]; // …
```
> ysh programmers 60061 기둥과보

- juneyoung/programmers/72410/P72410신규아이디추천.java
- juneyoung/programmers/72410/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72410)
1. 명세서에 맞춰서 구현하는 문제입니다.
2. 정규표현식과 replaceAll 함수를 이용하여 불필요한 문자를 제거했습니다.
- 시간복잡도: 최대 1000 * a ( a <= 1000 ) 
- O(N*a)
```java
public String solution(String new_id) {
StringBuilder sb = new StringBuilder();
String id = new_id.toLowerCase()
.replaceAll("[^a-z0-9-_.]", "")
.replaceAll("[.]{2,}", ".")
.replaceAll("^[.]|[.]$", "");
id = id.length() == 0 ? "a" : id;
id = id.length() >= 16 ? id.substring(0, 15) : id;
id = id.replaceAll("[.]$", "");
sb.append(id);
for (int i = sb.length(); i < 3; i++)
sb.append(sb.substring(sb.length() - 1));
return sb.toString();
}
}
```
- 정규표현식으로 풀이하니까 코드가 깔끔해졌습니다.
- 문자열 문제는 되도록 StringBuilder를 사용해서 풀이하는 게 좋은 것 같습니다.
> young programmers 72410 신규아이디추천

- myoung/programmers/42889/README.md
- myoung/programmers/42889/programmers_42889.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42889)
1. 실패율 구하기
- 실패율은 `해당 stage를 진행하고 있는 사람 수` / `해당 stage를 진행하고 있는 사람 수  + 해당 stage를 성공한 사람 수` 입니다.
- 이를 위해서 맨 마지막 stage부터 확인해서 total_user를 늘려주며 각 stage별 실패율을 계산했습니다.
2. 실패율을 기준으로 내림차순 정렬, 실패율이 같은 경우 stage번호를 기준으로 오름차순 정렬해주면 됩니다.
- 시간복잡도 : O(N^2) 
- 처음에 sort할 때 NlogN
- 그 다음 갯수 세면서 실패율 계산할 때 N^2
- 그 다음 sort할 때 NlogN
- 마지막에 답 도출할 때 N
-> 대략적으로 O(N^2)정도 걸린다구 생각했슴다
```python
def solution(N, stages):
answer = []
stages.sort()
stage_idx = len(stages) - 1
total_user = 0
for stage in range(N + 1, 0, -1):
now_user = 0
is_progress = False
if stage == N + 1:
while stage_idx >= 0 and stages[stage_idx] == stage:
total_user += 1
stage_idx -= 1
else:
while stage_idx >= 0 and stages[stage_idx] == stage:
is_progress = True
now_user += 1 …
```
> myoung programmers 42889 실패율

- jonghui/programmers_60061/README.md
- jonghui/programmers_60061/programmers_60061.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60061)
1. 기둥 - 바닥위인지 보의 한쪽 끝 위인지 다른기둥 위인지 체크
2. 보 - 한쪽 끝이 기둥 위인지 또는 양쪽 끝이 다른 보인지 체크
3. 기둥과 보를 순서대로 만들고 가능한지 체크 후 아니면 되돌림
- 시간복잡도 N^2 (1000번 다 생성일 경우 1000X1001X1/2)
```python
def check(answer):
for x, y, a in answer:
if a:
if (x,y-1,0) in answer or (x+1, y-1, 0) in answer or ((x-1,y,1) in answer and (x+1,y,1) in answer):
continue
else:
return False
else:
if y==0 or (x,y-1,0) in answer or (x-1,y,1) in answer or (x,y,1) in answer:
continue
else:
return False
return True
def solution(n, build_frame):
answer = set()
for x,y,a,b in build_frame:
if b:
answer.add((x,y,a))
if not check(answer):
answer.remove((x,y,a))
else:
answer.remove((x,y,a))
if not check(answer):
answer.add((x,y,a))
answer = list(map(list, answer))
return …
```
> Jonghui programmers 60061 기둥과 보 설치

- myoung/programmers/60057/README.md
- myoung/programmers/60057/programmers_60057.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60057)
1. 1개부터 (문자열의 길이//2)까지 문자열을 토막내서 압축 가능 여부를 확인합니다
2. 압축이 가능한 경우 압축시켜 새로운 문자열에 담아줍니다.
3. 만들어진 문자열 중 가장 짧은 문자열의 길이를 반환합니다.
- 시간복잡도 : O(N^2) 
- 문자열의 길이 N의 반만큼 반복하는데, 반복할 때마다 N개의 문자열을 모두 확인하기 때문에 O(N^2)입니다.
```python
def solution(s):
if len(s) == 1:
return 1
answer = 1000
for word_len in range(1, len(s)//2+1):
prev = s[:word_len]
cnt = 1
temp_word = ''
for j in range(word_len, len(s)+word_len, word_len):
now = s[j:j+word_len]
if prev == now:
cnt += 1
elif prev != now and cnt > 1:
temp_word += (str(cnt)+prev)
cnt = 1
prev = now
else:
temp_word += prev
prev = now
if cnt > 1:
temp_word += (str(cnt)+prev)
answer = min(len(temp_word), answer)
return answer
```
> myoung programmers 60057 문자열 압축

- seunghwan/programmers/60060/P60060가사검색.java
- seunghwan/programmers/60060/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/60060)
words와 queries 모두 총 길이 2 ~ 1000000으로 선형적으로 검사할 시 시간초과가 날 수 밖에 없다.
그래서 이 문제는 트라이 자료구조를 활용해서 풀이를 진행해야 한다.
트라이에 insert와 find 함수를 구현하며
이 문제에서는 특이하게 ?를 만나면 그 아래로는 모든 노드가 가능이다.
그래서 각 노드에 HashMap을 이용해 그 노드에 도달 했으면서 단어의 길이가 key인 갯수를 value로 저장해 주었다.
이렇게 하면 나중에 find를 할 때 ?를 만나면 해당하는 value만 return해주면 된다.
또 유의할 점으로
???do 같이 ?가 앞에서 부터 나오는 경우가 있으므로
트라이를 완전 거꾸로 보는 형태로도 하나 더 만들어
frodo -> odorf
???do -> od???
와 같이 작동하게 만들어 줘야 한다.
- 시간복잡도
O(N) word의 총길이 + 쿼리의 총길이
```java
import java.util.HashMap;
import java.util.Map;
public class P60060가사검색 {
class Trie {
Trie[] child = new Trie[26];
Map<Integer, Integer> lenMap = new HashMap<Integer, Integer>();
void insert(String s) {
Trie node = this;
lenMap.put(s.length(), …
```
> ysh programmers 60060 가사검색

- juneyoung/programmers/72411/P72411메뉴리뉴얼.java
- juneyoung/programmers/72411/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72411)
1. 고려해야할 사항 
- orders 배열 (20), orders 원소 (10), course 배열 (10) -> 완탐
- 문자열 조합 -> 카운팅 -> 정렬 -> 결과 순
- HashMap을 사용하여 key 는 문자열, value는 개수
- 해당 문자열 길이의 최대 개수를 담는 배열 필요.
2. 설계로직
1. HashMap을 사용하여 key 값은 문자열, value는 개수
2. 최대 문자열 길이가 10 이므로 부분집합으로 구해도 충분함.
- 부분집합을 구하는 방법 
1. 방문배열 사용한 재귀
2. 비트마스킹 ( 문자열 길이 제한 있음.)
- 리팩토링 : 조합으로 구하면 연산이 더 적음.
3. 부분집합으로 구한 모든 문자열중 course의 값에 해당하는 문자열 길이만 Map에 저장
4. 해당 문자열 길이의(코스요리의 개수) 최대 개수 갱신.
5. Map의 key값과 value값을 이용하여 코스요리의 개수가 2개 이상이고 최대값인 값들 추출 -> 정렬 -> String 배열로 변환
3. 시간복잡도
- 2^10(문자열 최대 길이) x 10 ( course 배열 길이) + NlogN(정렬) 
```java
static Map<String,Integer> map = new HashMap<>();
static int[] count = new int[11];
public String[] solution(String[] orders, …
```
> young programmers 72411 메뉴 리뉴얼

- HanJaehee/README.md
- HanJaehee/programmers72411.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72411)
1. 각 코스에서 **스카피** 가 요구하는 코스 길이에 해당하는 요리들을 조합으로 구해 모두 Map에 삽입
2. 모든 키를 탐색하며 각 코스 길이의 최대값을 구한다.
3. 해당 최대값과 같은 키들을 모두 정답으로 제출
- 시간복잡도 :
```java
public String[] solution(String[] orders, int[] course) {
List<String> result = new ArrayList<>();
Map<String, Integer> map = new HashMap<>();
for(int i=0; i<orders.length; ++i){ // 모든 order들을
for(int j=0; j<course.length; ++j){ // 문제에서 요구하는 course 수만큼
char[] orderChar = orders[i].toCharArray();
Arrays.sort(orderChar);
getOrders(orderChar, new boolean[orderChar.length], 0, orderChar.length, course[j], map); // 조합
}
}
int[] max = new int[course[course.length-1]+1];
for(String key : map.keySet()){
int len = key.length(); // 각 키의 길이는 요리의 개수를 의미 …
```
> HanJaehee Programmers 72411 메뉴 리뉴얼

- juneyoung/programmers/72413/P72413합승택시요금.java
- juneyoung/programmers/72413/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72413)
1. 고려해야할 사항 
- 지점갯수 (200), fares (200 * 199 / 2) , 요금 100,000 이하.
- 최단경로 탐색 알고리즘
2. 설계로직
1. 지점갯수가 200이하 이므로 플로이드-와샬(dp)로 해결할 수 있음.
- 플로이드-와샬은 다익스트라와 다르게 모든 시작점에서의 최소 거리를 알려주기 때문에 편리함.
2. 플로이드-와샬로 모든 정점에서 각각의 최소거리를 구함.
3. 'x 정점에서 A까지의 최소값' + 'x 정점에서 B까지의 최소값' + '시작점에서 x까지 최소값' -> 정답이 됨.
3. 시간복잡도: O ( n^3 ) 
```java
static int[][] cost;
static final int INF = 10000001;
public int solution(int n, int s, int a, int b, int[][] fares) {
cost = new int[n+1][n+1];
for(int i = 1; i <= n; i++) {
Arrays.fill(cost[i],INF);
cost[i][i] = 0;
}
for(int[] fare : fares) {
int start = fare[0];
int end = fare[1];
int c = fare[2];
cost[start][end] = cost[end][start] = Math.min(cost[start][end], c);
}
for(int …
```
> young programmers 72413 합승 택시 요금

- HanJaehee/programmers/72431/README.md
- HanJaehee/programmers/72431/programmers72431.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72413)
1. 경로를 나누어 생각했다.
Final = 택시 중간 하차 지점
case 1 : (Start - Final) + (Final - A) + (Final - B)
case 2 : (Start - A) + (Start - B)
2. 각 지점에서의 최단거리를 구해 전체 케이스의 최소값을 구하자.
- 시간복잡도 : E -> 최대 300, V -> 최대 n(n+1)/2, 3 \* O(ElogV)
```java
public class Point implements Comparable<Point>{
int v, cost;
Point(int v, int cost){
this.v=v;
this.cost=cost;
}
@Override
public int compareTo(Point p){
return Integer.compare(this.cost, p.cost);
}
}
public int solution(int n, int s, int a, int b, int[][] fares) {
List<Point>[] arr = new ArrayList[n+1];
for(int i=1; i<=n; ++i) arr[i] = new ArrayList<>();
for(int[] fare: fares){
arr[fare[0]].add(new Point(fare[1], fare[2]));
arr[fare[1]].add(new Point(fare[0], …
```
> HanJaehee Programmers 72413 합승 택시 요금

- juneyoung/programmers/72415/P72415카드짝맞추기.java
- juneyoung/programmers/72415/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72415)
1. 고려해야할 사항 
- board (4 x 4), 각 원소 ( 6 이하) -> 완탐 
2. 설계로직
1. board의 원소가 최대 6개 이므로 순열 사용.
2. 순서대로 현재 위치에서 최단거리로 탐색
-  매번 방문배열을 초기화 해서 사용 -> 같은 공간을 여러번 탐색 해야하기 때문
-  모든 경우의 수 마다 맵 생성 -> 짝을 맞출 경우 원소를 0 으로 초기화 해줘야 하기 때문
3. 짝을 맞춰야 하기 때문에 카드당 총 2회 탐색
- ctrl + 방향키 클릭 시 갈 수 있는 최대로 전진하기 때문에 신경써줘야 함 (이미 방문한 공간, 더이상 갈 수 없는 경우)
4. 짝을 맞춘 마지막 위치 + 최단 거리 리턴
- 다음번 카드짝을 찾으러 갈 경우 이전의 마지막 위치 정보를 알고 있어야 함.
- 최단거리는 합산
- 모든 카드 짝을 맞추지 않았지만 이전 결과보다 최단거리의 합이 클 경우 더이상 탐색하지 않아도 됨 (가지치기)
3. 시간복잡도: O ( 16(board 크기) x 6! ) 
```java
static int[] dr = {1,-1,0,0};
static int[] dc = {0,0,1,-1};
static Queue<Point> q = new LinkedList<>();
static int count, arr[], answer, map[][];
static boolean flag[], v[][];
static class …
```
> young programmers 72415 카드 짝 맞추기

- HanJaehee/programmers/72431/README.md
- HanJaehee/programmers/81301/README.md
- HanJaehee/programmers/81301/programmers81301.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81301)
1. 한 문자씩 순차적으로 돌면서 알파벳 소문자 'a' ~ 'z' 인 문자를 탐색한다.
2. 알파벳 소문자를 발견할 경우 해당 문자부터 인덱스를 증가시키며 문자를 StringBuilder에 담는다.
3. 문자열의 길이가 3이상일 경우 미리 Map에 담아둔 keySet()과 비교하며 일치할 경우 값을 리턴한다.
4. 반복
- 시간복잡도 : N(문자열의 길이)
```java
public int solution(String s) {
Map<String, Integer> map = new HashMap();
map.put("one", 1); map.put("six", 6);
map.put("two", 2);
map.put("four", 4); map.put("five", 5);
map.put("nine", 9); map.put("zero", 0);
map.put("seven", 7); map.put("three", 3);
map.put("eight", 8);
StringBuilder result = new StringBuilder();
StringBuilder tmp = new StringBuilder();
char chr;
int num;
for(int i=0; i<s.length(); ++i){
chr = s.charAt(i);
if(chr >= 'a' && chr <= 'z'){
tmp = new StringBuilder(); …
```
> HanJaehee Programmers 81301 숫자 문자열과 영어

- HanJaehee/programmers/72431/README.md
- HanJaehee/programmers/81301/README.md
- HanJaehee/programmers/81301/programmers81301.java
- HanJaehee/programmers/81303/README.md
- HanJaehee/programmers/81303/programmers81303.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81303)
1. D, U일 땐 각각 수만큼 증가
2. C일 땐 쓰레기통에 push 후 인덱스 - 1
3. Z일 떈 쓰레기통에서 꺼내와 삽입 후 현재 위치보다 작은 위치에 삽입되었으면 k 증가
4. 그 후 n 크기의 O으로 이루어진 문자열을 만든 후, 쓰레기통에 남아있는 숫자를 인덱스삼아 X삽입
- 시간복잡도 : N
```java
public String solution(int n, int k, String[] cmds) {
Stack<Integer> trash = new Stack<>();
for(String cmdStr : cmds){
char cmd = cmdStr.charAt(0);
if(cmd == 'D'){
k += Integer.valueOf(cmdStr.substring(2));
}else if(cmd == 'U'){
k -= Integer.valueOf(cmdStr.substring(2));
}else if(cmd == 'C'){
trash.push(k);
if(k == --n) k--;
}else if(cmd == 'Z'){
int removed = trash.pop();
if(removed <= k) k++;
n++;
}
}
StringBuilder sb = new StringBuilder();
for(int i=0; i<n; ++i) sb.append('O');
while(!trash.isEmpty()) …
```
> HanJaehee programmers 81303 표편집

- juneyoung/programmers/81303/P81303표편집.java
- juneyoung/programmers/81303/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81303)
1. 고려해야할 사항 
- n (1,000,000), cmd (200,000) -> 완탐 불가능. 
- cmd에 등장하는 모든 X들의 값을 합친 결과가 1,000,000 이하인 경우만 입력으로 주어집니다.
- 이동, 삭제 복구 연산.
- 사용할 자료구조 : 이중연결리스트, 스택
2. 설계로직
1. 이중연결리스트 자료구조 만들어야 함.
- 삽입 ( add ), 삭제 (delete), 이동 (prev, next) 매서드 필요.
- 주의점 : 첫번째 노드 삭제는 다른 노드 삭제와 다름.
2. 이중연결리스트에 데이터 n개만큼 add.
3. 마지막 인덱스 기준 현재위치 찾기.
4. 명령어 연산 실행
- U : X 수 만큼 prev( )
- D : X 수 만큼 next( )
- C : 스택에 해당 노드 추가 -> 현재 노드 delete( )
- Z :  스택에 top 에 있는 노드 꺼낸 후 리스트에 연결
```java
static Stack<Point> st = new Stack<>();    
public String solution(int n, int k, String[] cmd) {
Point p = new Point(0);
for(int i = 1; i < n; i++) {
p = p.add(new Point(i));
}
// 현재 위치 찾기.
for(int i = n-1; i > k; i--) …
```
> young programmers 81303 표 편집

- juneyoung/programmers/81305/P81305시험장나누기.java
- juneyoung/programmers/81305/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81305)
1. 고려해야할 사항 
- 나눌 그룹의 수 k (10,000) , 응시자 수 num (10,000)
- 정확성 테스트 케이스는 20, 20 이므로 모든 경우를 탐색할 수 있음 20C10 -> 약 18만
- 최소화된 최대 그룹의 인원을 계산. -> 파라메트릭 서치
- 최적화 문제를 결정문제로 바꿈
- 최대 그룹의 인원을 계산해야 하므로 기준값 이상은 모두 참이라고 생각할 수 있음. -> 이분 탐색
2. 설계로직
1. 간선 리스트 만들기
- 이진트리라서 1차원 배열로 최적화 가능
2. 루트 노드 찾기
3. 이분탐색 시작
- 이분탐색의 최소값은 모든 (시험장의 인원 / k)
- 이분탐색의 최대값은 모든 시험장의 인원
4. 재귀를 이용해 단말노드부터 계산 시작
- 시험장 수 만큼 2차원 배열 생성 
- 0번 -> 나를 포함한 자식노드의 그룹 개수
- 1번 -> 나를 포함한 그룹의 최소값
- 자식 노드가 없을 때 ( 단말노드 ) 
- 자식 노드가 1개
- 자식 노드가 2개
5. 공통 계산과정
- 왼쪽 자식 값 (1번 인덱스)  + 오른쪽 자식의 값 (1번 인덱스) + 현재 시험장의 인원의  <= 기준 값
-> 같은 그룹으로 묶임.
-> 그룹수는 자식 노드 그룹 수 합 - 1
- (왼쪽 자식의 값 + 현재 시험장의 인원)  <= 기준 값 OR (오른쪽 자식의 값 + 현재 시험장의 인원) <= 기준 값
-> 두 값중 작은 값으로 묶임.
-> 한 쪽만 잘라내면 되기 때문에 그룹수는 자식 노드의 그룹 수 합 …
> young programmers 81305 시험장 나누기

- juneyoung/programmers/81302/P81302거리두기확인하기.java
- juneyoung/programmers/81302/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81302)
1. 고려해야할 사항 
- places 배열 (5 x 5) -> 완탐
- 맨해튼 거리 2
2. 설계로직
1. 너비 우선 탐색을 이용하여 depth가 2 인 너비우선 탐색 -> 맨해튼 거리가 2
2. '배열크기를 벗어나는경우' or '이미 지나왔던 위치' or '파티션' 이면 패스
3. 너비 우선 탐색중 'P' 를 발견했다면 거리두기가 지켜지지 않음.
3. 시간복잡도: O ( 5 x 5 x bfs탐색(13)) 이하 
```java
static int[] dr = {1, -1, 0, 0}; 
static int[] dc = {0, 0, -1, 1};
static boolean[][] v;
static Queue<Point> q = new LinkedList<>();
static char[][] map = new char[5][];
static class Point {
int r, c, depth;
public Point(int r, int c, int depth) {
this.r = r;
this.c = c;
this.depth = depth;
}
}
public int[] solution(String[][] places) {
int[] answer = new int[places.length];
Arrays.fill(answer, 1);
for(int i = 0; i < places.length; i++) {
for(int j = …
```
> young programmers 81302 거리두기 확인하기

- HanJaehee/programmers/72431/README.md
- HanJaehee/programmers/81301/README.md
- HanJaehee/programmers/81301/programmers81301.java
- HanJaehee/programmers/81302/README.md
- HanJaehee/programmers/81302/programmers81302.java
- HanJaehee/programmers/81303/README.md
- HanJaehee/programmers/81303/programmers81303.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/81302)
1. 각 지도별로 모든 P에 bfs를 수행
2. P에서 시작해 거리 2이하에서 P를 마주쳤을 때 지나온 길 중 파티션을 만나지 않았다면, false 리턴
- 시간복잡도 : 최대 5*5(맵크기) * 3*3(점 주변) * 5(전체 사이즈)
```java
public int[] solution(String[][] places) {
int[] answer = new int[places.length];
char[][] map = new char[5][];
for(int i=0; i<places.length; ++i){
for(int j=0; j<5; ++j){
map[j] = places[i][j].toCharArray();
}
answer[i] = isRight(map);
}
return answer;
}
public int isRight(char[][] map){
for(int i=0; i<5; ++i){
for(int j=0; j<5; ++j){
if(map[i][j] == 'P'){
if(!check(map, i, j)) return 0;
}
}
}
return 1;
}
class Point{
int y, x, count;
boolean partition;
Point(int y, int x, int count, boolean partition){
this.y = y;
this.x = x;
this.count = count; …
```
> HanJaehee programmers 81302 거리두기 확인하기

- juneyoung/programmers/64061/P64061크레인인형뽑기게임.java
- juneyoung/programmers/64061/README.md
1. 고려해야할 사항 
- board 배열 (30 x 30), moves (1,000) -> 완탐 가능
- 스택 사용
2. 설계로직
1. board 배열에서 해당 열(moves 값) 검색
- 0일 경우 패스
- 0이 아닐경우 stack의 peek값을 확인
- 값이 같으면 answer+2, pop
- 값이 다르면 push
- 배열 0으로 초기화
3. 시간복잡도: O (1,000 x 30) 
```java
static int answer;
static Stack<Integer> st = new Stack<>();
public int solution(int[][] board, int[] moves) {
st.push(-1);
for(Integer move : moves) {
cal(board,move-1);
System.out.println(answer);
}
return answer;
}
static void cal(int[][] board, int move) {
for(int col = 0; col < board[0].length; col++) {
if(board[col][move] == 0) continue;
else {
if(st.peek() == board[col][move]) {
answer += 2;
st.pop();
}else st.push(board[col][move]);
board[col][move] = 0; …
```
> young programmers 64061 크레인 인형뽑기 게임

- juneyoung/programmers/64064/P64064불량사용자.java
- juneyoung/programmers/64064/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64064)
1. 고려해야할 사항 
- user_id 배열 ( 8 ) & 8이하의 문자열, banned_id 배열 ( 8 ) -> 완탐
- 순열 or 조합 사용해서 풀이할  수 있음.
2. 설계로직
1. 중복을 피하기위해 Set과 특정 값 배열 사용 
- 비트마스킹과 같은 원리
2. 순열로 모든 문자열 경우의 수 구하기
3. banned_id와 비교 -> 완탐
4. 문자열 조합이 될 경우 값으로 변환 후 set에 저장
5. set 갯수 리턴
3. 시간복잡도: O (n!) 
```java
static Map<String,Integer> map = new HashMap<>();
static Set<Integer> set = new HashSet<>();
static List<Integer> key = Arrays.asList(8,80,800,8000,80000,800000,8000000,80000000);
static String[] result;
static int size;
static boolean[] v;
public int solution(String[] user_id, String[] banned_id) {
size = banned_id.length;
result = new String[size];
v = new boolean[user_id.length];
for(int i = 0; i < …
```
> young programmers 64064 불량 사용자

- HanJaehee/programmers/64061/README.md
- HanJaehee/programmers/64061/programmers64061.java
- HanJaehee/programmers/81302/README.md
- HanJaehee/programmers/81302/programmers81302.java
1. 스택을 활용해 그대로 구현했다.
- 시간복잡도 : N^2
```java
import java.util.Stack;
public int solution(int[][] board, int[] moves) {
int picked, idx, answer = 0;
Stack<Integer> s = new Stack<Integer>();
int[] tmp;
for (int cmd : moves) {
cmd--;
tmp = rtoc(board, cmd);
idx = getDoll(tmp);
if (idx == -1)
continue;
picked = board[idx][cmd];
board[idx][cmd] = 0;
if (!s.isEmpty() && s.peek() == picked) {
answer += 2;
s.pop();
continue;
}
s.add(picked);
}
return answer;
}
private int[] rtoc(int[][] board, int num) {
int[] arr = new int[board.length];
for (int j = 0; j < board.length; j++) {
arr[j] = board[j][num];
}
return arr;
}
private int getDoll(int[] arr) {
for (int i = 0; i < arr.length; i++) {
if (arr[i] != 0) {
return i; …
```
> HanJaehee Programmers 64061 크레인 인형뽑기 게임

- seunghwan/programmers/64062/P64062징검다리건너기.java
- seunghwan/programmers/64062/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64062)
삽질
처음엔 슬라이딩 윈도우로
K크기 만큼 보면서 K크기 안의 최댓값 중 최소값을 구하는 방법으로 풀이했는데
K * (N-K) 만큼 연산을 하므로
N = 20만 K = 10만 인 경우
100억이 나오므로 시간초과가 떳다.
그런데 다른 사람의 풀이에서 보니
매번 최대값 검색 후 다음 슬라이딩윈도우 시작 위치를 최대값 위치로 옮겨줘서 풀린 코드가 있었는데
내림차순으로 정렬된 N=20만 K=10만이면 똑같이 시간초과가 나야하는데 풀린걸 보니
테케가 조금 부실했나보다
\-----------------------------------------------------------------------------
이 문제는 처음 겪어본 문제라 조금 당황한 문제이다.
Stones의 길이 20만에 집중할 것이 아닌
Stones의 크기 범위 2억을 줄여 풀이해야 하는 문제
즉 파라메틱 서치를 이용하는데
조건에 만족하는 최적의 값을 구하는 이분탐색? 정도로 보면 될 것 같다.
조건은 20만개안에서 K 크기 만큼의 빈칸이 생겨났는지 이고
값은 1 ~ 2억에서 반씩 줄여가면서
1억에서 가능한지 불가능한지
가능하다면 1억 이전의 값들도 모두 가능하므로
left를 1억으로 옮기고 1억+1 ~ 2억
불가능하다면 1억 이후의 값들은 모두 불가능하므로
right를 1억으로 옮겨 1 ~ 1억 -1
이런식으로 불가능한 최소값을 이분탐색으로 찾아간다.
실제로는 1~2억을 다 할 필요없이
배열을 한번 돌면서 최소값 ~ 최대값 형태로 …
> ysh programmers 64062 징검다리 건너기

- juneyoung/programmers/64063/P64063호텔방배정.java
- juneyoung/programmers/64063/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64063)
1. 고려해야할 사항 
- k 엄청 큰 수, room_number 배열( 200,000 ) -> 완탐 불가능, 배열생성 불가능
- 자료구조 필요.
2. 설계로직
1. HashMap 사용 -> key : 현재 방, value : 가능한 다음 방
2. 재귀함수를 통해 Union - Find 알고리즘 구현
1. map에 현재 값이 없으면 저장
2. 있으면 재귀를 돌면서 가능한 방을 찾음. 
-> 입력받은 숫자와 다음 가능한 방으로 연결 ( 최적화 )
```java
static Map<Long,Long> map = new HashMap<>();
public long[] solution(long k, long[] room_number) {
long[] answer = new long[room_number.length];
for(int i = 0; i < room_number.length; i++) {
answer[i] = cal(room_number[i]);
}
return answer;
}
public static long cal(long num){
if(!map.containsKey(num)){
map.put(num,num+1);
return num;
}
long findNum = cal(map.get(num));
map.put(num, findNum+1);
return findNum;
}
} …
```
> young programmers 64063 호텔 방 배정

- juneyoung/programmers/64065/P64065튜플.java
- juneyoung/programmers/64065/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/64065)
1. 고려해야할 사항 
- s 문자열 1,000,000 -> 선형탐색
- 카운팅할 자료구조 ( Array, Map ) 
2. 설계로직
1. HashMap 사용 -> key : 원소, value : 갯수
2. 괄호 사이의 문자열을 분리해 배열로 만들기
3. 각 배열의 문자를 Hash맵에 저장 & 카운팅
4. 역순 정렬
5. 출력
3. 시간복잡도: O (n x logn) 
```java
static Map<String,Integer> map = new HashMap<>();
public int[] solution(String s) {
for(int i = 1; i < s.length(); i++) {
if(s.charAt(i) == '{'){
int idx = i;
while(s.charAt(idx) != '}') idx++;
Arrays.stream(s.substring(i+1,idx).split(","))
.forEach(o -> map.merge(o,1,Integer::sum));
i = idx;
}
}
return map.keySet().stream()
.sorted((o1,o2) -> map.get(o2) - map.get(o1))
.mapToInt(Integer::parseInt)
.toArray();
}
}
```
- 문자열만 잘 처리하면 풀리는 문제.
> young programmers 64065 튜플

- seunghwan/programmers/72411/P72411메뉴리뉴얼.java
- seunghwan/programmers/72411/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/72411)
1. 고려해야 할 사항
- orders의 크기 20
- orders의 각 원소 크기 10
- course의 크기 10
크기가 작아 완탐 가능
2. 설계 로직
- 메뉴 구성에 따라 따로 저장하기 위한 HashMap의 배열 생성
- HashMap의 key는 String , value는 Integer (메뉴구성, 갯수)
- 각 주문목록을 조합으로만 뽑기 위해 알파벳 오름 차순 정렬
- 조합을 뽑고 해당하는 길이의 HashMap배열에서 HashMap을 뽑아 갯수 ++
- ex) ABC 에서 AB를 뽑았으면 maps[2]의 HashMap에 AB +1
- course에서 찾는 길이의 HashMap을 가져와서 1이상의 최댓값 검색
- 해당하는 key들을 하나의 List에 저장 후 정렬
3. 시간 복잡도
- N = 2^10 * 20(조합 최대 갯수)
- O(NlogN)
```java
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
public class P72411메뉴리뉴얼 {
Map<String, Integer> maps [] = new Map[21];
int [] Max = new int[21];
public String[] solution(String[] orders, …
```
> ysh programmers 72411 메뉴리뉴얼

- juneyoung/programmers/67257/P67257수식최대화.java
- juneyoung/programmers/67257/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67257)
1. 고려해야할 사항 
- expression 길이 (100) , 연산기호 최대 3개 -> 완탐
2. 설계로직
1. 인덱스로 계산하기 위해 ArrayList사용
2. 연산기호와 숫자를 분리해 각각 ArrayList로 저장
3. 순열을 통해 연산기호의 순서를 정함
4. 순열의 결과에 따라 연산하여 최대값 갱신
3. 시간복잡도: O (3! x 3 x n) -> 정확하지 않음.  
```java
import java.util.stream.*;
static List<Long> numbers;
static List<String> opers = new ArrayList<>();
static String[] sign = {"-","*","+"}, arr = new String[3];
static boolean[] v = new boolean[3];
static long answer = Long.MIN_VALUE;
public long solution(String expression) {
for(int i = 0; i < expression.length(); i++) {
if(expression.charAt(i) - '0' < 0) opers.add(expression.charAt(i)+"");
}
numbers = Arrays.stream(expression.replaceAll("[^0-9]"," ").split(" ")) …
```
> young programmers 67257 수식 최대화

- juneyoung/programmers/67259/P67259경주로건설.java
- juneyoung/programmers/67259/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67259)
1. 고려해야할 사항 
- board 배열 (25 x 25) 
- 중복해서 방문 가능하기 때문에 방문배열에 신경써야 함.
- 이전에 방향을 기억해야 함.
2. 설계로직
1. 메모이제이션을 이용해야 하기 때문에 방문배열을 int로 만듦.
2. ( 0,0 ) 부터 탐색 시작.
3. 이동
1. 이전의 방향과 현재의 방향이 같다면 + 100
2. 이전의 방향과 현재의 방향이 다르다면 ( 코너 ) + 600
3. 방문배열로 현재 위치까지의 값보다 작은 경우만 이동해야 함.
3. 시간복잡도: O ( n^2 x a )
```java
static int[] dr = {-1, 1, 0, 0};
static int[] dc = {0, 0, -1, 1};
static int answer = Integer.MAX_VALUE;
static Queue<Point> q = new LinkedList<>();
static class Point {
int r, c, cnt, dir;
public Point(int r, int c, int cnt, int dir) {
this.r = r;
this.c = c;
this.cnt = cnt;
this.dir = dir;
}
}
public int solution(int[][] board) {        
cal(board);
return answer;
}
public static void cal(int[][] …
```
> young programmers 67259 경주로 건설

- juneyoung/programmers/67256/P67256키패드누르기.java
- juneyoung/programmers/67256/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67256)
1. 고려해야할 사항 
- numbers 배열 (1,000) -> 완탐
- Map사용
2. 설계로직
1. HashMap 사용 -> key : 키패드 숫자, value : 좌표 ( row, col )
2. 키패드의 좌표를 map에 저장
3. 계산
1. 숫자 2, 5, 8, 0 일 경우 좌표의 절대값 계산으로 결과를 구함.
```java
import java.util.stream.*;
static int leftNum = 10, rightNum = 11;
static Map<Integer,Point> map = new HashMap<>();
static class Point{
int r,c;
public Point(int r, int c){
this.r = r;
this.c = c;
}
}
public String solution(int[] numbers, String hand) {
init();        
return Arrays.stream(numbers)
.mapToObj(i -> cal(i,hand))
.collect(Collectors.joining());
}
public static void init() {
map.put(1,new Point(1,1)); map.put(2,new Point(1,2)); map.put(3,new Point(1,3));
map.put(4,new …
```
> young programmers 67256 키패드 누르기

- juneyoung/programmers/67260/P67260동굴탐험.java
- juneyoung/programmers/67260/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67260)
1. 고려해야할 사항 
- n ( 200,000 ) -> 선형탐색으로 해결 
- 트리형태의 탐색문제 -> bfs일 확률이 높음.
- 방문 시 우선순위가 있음. -> 1차원 방문배열하나로 해결하기 힘들 수 있음.
2. 설계로직
1. 우선순위를 해결하기 위해 HashMap 사용 , 이전 노드를 갔다 왔는지 확인하기 위해 prev 배열 사용
1. A -> B 인 map과
2. B -> A 인 revMap 사용 ( 선행 노드를 확인하기 위해 )
2. 시작점이 0 이기 때문에 0부터 큐에 add
3. 해당 노드에서 갈 수 있는 노드 확인
1. 이전 노드를 방문했다고 표시
2. 이미 방문했거나, 선행노드를 방문하지 않았다면 (revMap 사용) 패스~
3. 그외 모든 노드들 큐에 저장
4. 해당 노드가 선행 노드일 경우, 후행 노드의 이전 노드를 방문했다면 큐에 저장
3. 시간복잡도: O ( n  + E ) 
```java
static List<Integer>[] list;
static boolean[] v, prev;
static Map<Integer,Integer> map = new HashMap<>(), revMap = new HashMap<>();
public boolean solution(int n, int[][] path, int[][] order) {
boolean answer = true;
list = new …
```
> young programmers 67260 동굴 탐험

- swanious/programmers/67260/Readme.md
- swanious/programmers/67260/programmers_67260.js
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/67260)
1. 설계로직
- bfs 활용 (dfs의 경우 rootNode로 다시 돌아올 경우 방문체크가 힘들었습니다..)
2. 고려해야할 사항
- 선 방문 노드가 있을 경우 배열에 임시(접근금지)로 저장하고 continue
- 선 방문 노드에 도달했을 때 이후 방문할 노드를 q에 삽입하기(접근금지 해제)
3. 시간복잡도 O(N + E) - 확실하지 않음
```javascript
class Node {
constructor(val) {
this.val = val;
this.next = null;
}
}
class Queue {
constructor() {
this.head = null;
this.tail = null;
this.size = 0;
}
push(val) {
const newNode = new Node(val);
// 비었으면 head/tail 모두 newNode
if (!this.head) {
this.head = newNode;
this.tail = newNode;
} else {
this.tail.next = newNode;
this.tail = newNode;
}
this.size++;
}
pop() {
// 비었으면 null반환
if (!this.head) return null;
const temp = this.head;
// 값이 1개 존재하면 tail = null
if (this.head === this.tail) {
this.tail = null;
}
this.head = …
```
> swanious programmers 67260 동굴탐험

- swanious/programmers/42577/programmers_42577.py
- swanious/programmers/42577/readme.md
- swanious/programmers/42579/programmers_42579.js
- swanious/programmers/42579/readme.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42579)
1. object에 모든 정보를 저장
-  `{total : 0, arr: [[idx1, play1], [idx2, play2], ...] }` 형태로 저장했다
2. 장르, 재생 수, 고유번호 순으로 정렬한다.
- 재생횟수가 같은 경우에 고유번호가 작은 순서대로 정렬할 필요 x (index 순서대로 push했으므로)
```javascript
function solution(genres, plays) {
var answer = [];
const obj = {};
for (let i = 0; i < genres.length; i++) {
if (!obj[genres[i]]) obj[genres[i]] = {total : 0, arr: [] };
obj[genres[i]].total += plays[i]
obj[genres[i]].arr.push([i, plays[i]]);
}
const newArr = Object.entries(obj).sort((a, b) => b[1].total - a[1].total); // 총 합계 내림차순
newArr.forEach(([genre, object]) => {
const arr = object.arr.sort((a, b) => b[1] - a[1]);
const l = arr.length >= 2 ? 2 : arr.length; // 배열의 크기가 2보다 작으면 배열의 크기만큼
for (let i = 0; i < l; i++) { …
```
> swanious programmers 42579 베스트앨범

- swanious/programmers/42626/programmers_42626.py
- swanious/programmers/42626/readme.md
- swanious/programmers/42627/programmers_42627.js
- swanious/programmers/42627/readme.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42626)
```
섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
```
- heapq 모듈 사용해서 배열을 최소힙으로 저장
- 2개를 빼서 위의 계산식으로 값을 구하고 다시 heap에 저장 반복
- while문 안의 배열의 길이가 2보다 작으면 -1리턴
```python
import heapq
def solution(scoville, K):
heap = []
cnt = 0
for s in scoville:
heapq.heappush(heap, s)
while heap[0] < K:
if len(heap) > 1:
heapq.heappush(heap, heapq.heappop(heap) + (heapq.heappop(heap) * 2))
else: return -1
cnt += 1
return cnt
```
- heapq 모듈을 활용해서 풀 수 있었다. 파이썬 짱..
> swanious programmers 42626 더맵게

- swanious/programmers/42627/programmers_42627.js
- swanious/programmers/42627/readme.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42627)
1. 처음에 **요청 시점** 오름차순 정렬
2. 시간이 겹치는 작업
3. **소요 시간**이 더 적은 작업을 먼저 처리하도록 q를 오름차순 정렬
- q에 2개 이상의 작업이 추가된다는 것 -> 시간이 겹친다는 의미
- 이 때, 작업시간이 더 적은 작업을 먼저 처리해야함
4. 겹치지 않으면 총소요시간(total)은 다음 작업의 시작시점으로 초기화
- 시간복잡도: O(n^2 logn)
```javascript
function solution(jobs) {
jobs.sort((a, b) => a[0] - b[0]);
let q = [];
let total = 0;
let duration = 0;
const l = jobs.length;
while (jobs.length || q.length) {
while (jobs[0] && jobs[0][0] <= total) {
q.push(jobs.shift())
}
// 시간이 소요 순서로 오름차순 정렬 ([2, 6] -> [1, 9])
q.sort((a, b) => a[1] - b[1]);
if (q.length > 0) {
const temp = q.shift()
total += temp[1];
duration += total - temp[0]
} else total = jobs[0][0] // 작업이 겹치치 않으면 total은 다음 작업의 시작시점
}
return Math.floor(duration / l);
};
```
- jobs의 길이가 …
> swanious programmers 42627 디스크 컨트롤러

- seunghwan/boj/3197/G1_3197백조의호수.java
- seunghwan/boj/3197/README.md
[문제 링크](https://www.acmicpc.net/problem/3197)
1. 각 빙판이 녹는데 필요한 시간들을 탐색 후 배열에 저장
2. 백조 한마리부터 bfs를 돌며 다른 백조를 찾을 때까지 탐색
2-1. bfs를 돌며 빙판을 지나갈 때는 그 빙판이 녹는 day와 지금껏 지나온 빙판의 day중 더 큰 것 저장. 
2-2. PriorityQue를 이용해 저장한 day가 가장 작은 것부터 탐색.
3. 다른 백조를 만나면 바로 종료 후 저장 된 day 출력
4. 끝.
- 시간복잡도
O(N^2)    (N = map의 한 변)
```java
package Gold;
import java.awt.Point;
public class G1_3197백조의호수 {
static char[][] map;
static int[][] dayMap;
static int R, C;
static Queue<Point> water = new LinkedList<Point>();
static Point bird1, bird2;
static class node implements Comparable<node> {
int x;
int y;
int day;
public node(int x, int y, int …
```
> ysh boj 3197 백조의호수

- seunghwan/programmers/42628/P42628이중우선순위큐.java
- seunghwan/programmers/42628/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42628)
뭔가 Deque와 정렬을 쓰면 쉽게 해결 될 거 같은데
제목이 이중우선순위큐니깐 우선순위큐를 써서 해결해 보려고
우선순위큐 2개를 사용했다.
\1. 숫자와 이 숫자가 유효한지 확인하는 isok를 가진 class 정의
\2. 오름차순 minPq와 내림차순 maxPq 준비
\3. operations의 연산자에 따라
3-1. 입력이면 minPq와 maxPq에 모두 넣기
3-2. d 1 이면 maxPq에서 d -1 이면 minPq에서 하나 빼기
3-2-1. Pq에서 뺄 때 isok가 true라면 isok를 false로 바꾸기
3-2-2. isok가 false라면 true를 뽑을 때까지 뽑기
\4. 모든 연산을 마치고 d 1과 d -1 작업을 한번 더 해서 max값과 min값 꺼내기
\5. max min 값 배열에 담아 return
- 시간복잡도
O(NlogN) 
```java
import java.util.Comparator;
public class P42628이중우선순위큐 {
class node{
int num;
boolean isok;
public node(int num, boolean isok) {
this.isok = isok;
}
}
public int[] solution(String[] operations) {
PriorityQueue<node> minPq = new …
```
> Ysh programmers 42628 이중우선순위큐

- seunghwan/programmers/42626/P42626더맵게.java
- seunghwan/programmers/42626/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42626)
코딩 테스트 연습 heap 1번문제
Priority Queue 를 쓰면 쉽게 해결 가능하다.
pq를 이용해 오름차순에서 2개를 꺼내고
이 조건에 맞춰 다시 넣어주고
만약 pq에서 처음으로 꺼낸 수가
k를 넘어가면 끝내면 된다.
- 시간복잡도
O(N) 
```java
public class P42626더맵게 {
public int solution(int[] scoville, int K) {
PriorityQueue<Integer> pq = new PriorityQueue<Integer>();
for(int i : scoville)
pq.add(i);
boolean flag = true;
while(!pq.isEmpty()) {
int f = pq.poll();
if(f >=K)
break;
if(pq.isEmpty()) {
flag = false;
break;
}
int s = pq.poll();
pq.add(f+s*2);
answer++;
}
return flag ? answer : -1;
}
}
```
- pq 사용에 가장 기본적인 문제였다.
> Ysh programmers 42626 더 맵게

- seunghwan/programmers/42627/P42627디스크컨트롤러.java
- seunghwan/programmers/42627/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42627)
대기 시간을 가장 줄이는 방법은
현재 시간에 작업을 시작할 수 있는 작업 중 걸리는 시간이 가장 짧은 것 부터 작업을 하면 된다.
걸리는 시간이 가장 짧은 것을 찾기 위해 pq를 활용하면 쉽게 해결 가능하다.
\1. jobs를 시작시간에 맞춰 오름차순 정렬한다.
\2. 현재 시간에 작업이 가능한 작업들을 pq에 집어 넣는다.
\3. pq에서 작업 시간이 제일 작은 작업을 빼서
\4. 시간을 지나게 하고 (지나간 시간 - 작업이 들어온 시간) 을 answer에 + 한다.
\5. 작업의 갯수를 cnt에 저장하고
\6. 모든 작업이 끝나고 answer / cnt 를 return 한다.
- 시간복잡도
O(nlogn)
```java
import java.util.Comparator;
public class P42627디스크컨트롤러 {
class job {
int start;
int end;
job(int start, int end) {
this.start = start;
this.end = end;
}
}
public int solution(int[][] jobs) {
PriorityQueue<job> pq = new PriorityQueue<>(new Comparator<job>() {
@Override
public int compare(job o1, job o2) {
return o1.end - …
```
> Ysh programmers 42627 디스크 컨트롤러

- juneyoung/programmers/42862/P42862체육복.kt
- juneyoung/programmers/42862/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42862)
1. 고려해야할 사항 
-  전체 학생의 수는 2명 이상 30명 이하
- 여벌 체육복을 가져온 학생이 체육복을 도난당했을 수 있습니다. 이때 이 학생은 체육복을 하나만 도난당했다고 가정하며, 남은 체육복이 하나이기에 다른 학생에게는 체육복을 빌려줄 수 없습니다.
2. 설계로직
1. 체크배열을(v) 사용하여 체육복을 도난당한 학생들을 표시.
2. 여벌 체육복이 있는 학생들의 리스트를 담을 수 있는 HashSet사용
3. 고려해야할 사항2번째 로직을 처리하기 위해 v배열을 확인하여 HashSet의 정보를 remove
4. 체육복을 도난당한 학생들의 앞 뒤를 검사하여 빌릴 수 있는지 판단
```kotlin
fun solution(n: Int, lost: IntArray, reserve: IntArray): Int {
var answer = n
val reserveSet: HashSet<Int> = hashSetOf()
val v = Array(n + 1) { true }
for (i in lost) {
v[i] = false
answer--
}
for (idx in reserve.indices) {
reserveSet.add(reserve[idx])
if (!v[reserve[idx]]) {
v[reserve[idx]] = true
reserveSet.remove(reserve[idx])
answer++
}
}
for (idx in …
```
> young programmers 42862 체육복

- seunghwan/programmers/42884/P42884단속카메라.java
- seunghwan/programmers/42884/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42884)
프로그래머스 그리디 마지막 문제
\1. 나가는 위치 순으로 정렬
\2. 마지막 설치 지점을 저장할 변수하나 선언 후 최소값 -30001로 저장
\3. 앞에서부터 순서대로 꺼내면서
3-1. 마지막 설치지점보다 시작지점이 뒤라면 나가는 지점에 카메라 설치
3-2. 마지막 설치지점보다 시작지점이 앞이라면 이미 앞의 카메라로 단속이 가능하므로 continue
\4. 설치한 카메라 수 return 
- 시간복잡도
O(n)
```java
import java.util.Comparator;
public class Solution {
public int solution(int[][] routes) {
int nowPlace = -30001;
Arrays.sort(routes,new Comparator<int []>() {
@Override
public int compare(int[] o1, int[] o2) {
return o1[1] - o2[1];
}
});
//도착지점 앞인 얘 하나 꺼내고
//현재 위치보다 시작이 앞서 있으면 버리고
//시작이 뒤면 현재 위치를 이 녀석의 도착지점으로 바꾸기
for(int i = 0 ; i < routes.length; i++) {
int [] now = routes[i];
if(now[0] <= nowPlace)
continue;
answer++;
nowPlace = now[1];
} …
```
> Ysh programmers 42884 단속카메라

- swanious/programmers/42626/programmers_42626.py
- swanious/programmers/42626/readme.md
- swanious/programmers/42627/programmers_42627.js
- swanious/programmers/42627/readme.md
- swanious/programmers/programmers_42628.js
- swanious/programmers/readme.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42628)
- I일때 -> 배열에 삽입 후 오름차순 정렬
- D일때 -> 최소값일때 왼쪽에서 뽑고, 최대값일때 오른쪽에서 뽑아준다.
- 모든 작업이 끝나고 다시 queue를 오름차순 해준다.
- 큐에 값이 있다 ? [최대값, 최소값] : [0, 0]
```javascript
function solution(operations) {
var queue = [];
operations.forEach((op) => {
const [command, val] = op.split(' ')
if (command === "I") {
// Number로 변환
queue.push(val * 1)
}
else if (command === 'D' && queue.length) {
queue.sort((a, b) => a - b)
val === '1' ? queue.pop() : queue.shift()
}
})
queue.sort((a, b) => a - b)
return queue.length ? [queue[queue.length-1], queue[0]] : [0, 0];
}
```
- js에는 파이똔의 deque같은 핵꿀 라이브러리는 없지만, 정렬과 shift()만 있다면 충분히 이중우선순위큐를 만들 수 있다.
> swanious programmers 42628 이중우선순위큐

- HanJaehee/programmers/42885/README.md
- HanJaehee/programmers/42885/programmers42885.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42885)
1. 오름차순으로 정렬
2. 오른쪽 사람은 항상 내린다.
3. 왼쪽의 사람은 오른쪽 내리는 사람과 무게를 합했을 때, 제한이 넘지 않아야 내린다.
```java
public int solution(int[] people, int limit) {
Arrays.sort(people);
int end = people.length -1;
int start = 0;
while(end >= start){
int weight = people[end--];
if(weight + people[start] <= limit)
start++;
answer++;
}
return answer;
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 문제였습니다.
> HanJaehee Programmers 42885 구명보트

- HanJaehee/programmers/42883/README.md
- HanJaehee/programmers/42883/programmers42883.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42883)
1. 먼저, 어떤 수에서 k개의 수를 제거한 수의 길이를 result_len이라고 할 때,
2. 어떤 수의 가장 앞자리부터 result_len까지 중 가장 큰 수를 찾는다. 그것이 우리가 구하려는 가장 큰 수 의 가장 앞자리가 된다.
3. 이후 구한 수의 가장 뒷자리부터 지속적으로 큰수를 찾아 result_len만큼 반복하면 가장 큰 숫자를 구할 수 있다.
- 시간복잡도 : N
```java
public String solution(String number, int k){
StringBuilder result = new StringBuilder();
char[] numbers = number.toCharArray();
int len = numbers.length - k;
int pos = 0;
while(len > 0){
char max = ' ';
for(int i=pos; i<=numbers.length - len; ++i){
if(numbers[i] > max){
max = numbers[i];
pos = i;
}
}
result.append(max);
pos++;
len--;
}
return result.toString();
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 문제였습니다.
> HanJaehee Programmers 42883 가장 큰 수 

- HanJaehee/programmers/42860/README.md
- HanJaehee/programmers/42860/programmers42860.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42860)
1. 전체 반복횟수는 name의 길이에서 A의 갯수를 뺀 횟수
2. 먼저, 알파벳 변경 횟수를 answer에 모두 더해놓으면서, 전체 반복횟수를 구한다.
3. 왼쪽 이동거리와 오른쪽 이동거리를 측정해 더 짧은 쪽으로 이동하면서 이동 횟수를 누적한다.
4. 두 경우가 같을경우엔 오른쪽을 우선으로 한다.
- 시간복잡도 : N
```java
public int solution(String name) {
int count = name.length();
char[] charName = name.toCharArray();
boolean[] isFinish = new boolean[charName.length];
int now = 0;
int next = 0;
for(int i=0; i<charName.length; ++i){ // 알파벳 변경
if(charName[i] == 'A') count--;
answer += Math.min(charName[i] - 'A', 'Z' - charName[i] +1);
}
for(int i=0; i<count; ++i){ // 이동 거리
int left = 0, right = 0;
int leftCount = 0, rightCount = 0;
int idx = now;
while(leftCount < charName.length){
if(idx == isFinish.length) idx = 0; …
```
> HanJaehee Programmers 42860 조이스틱

- HanJaehee/programmers/42862/README.md
- HanJaehee/programmers/42862/programmers42862.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42862)
1. 체육복을 잃은 사람들과, 여분을 가진 사람들의 배열을 만든 후
2. 순서를 보장받지 않았기 때문에 reserve를 정렬한다.
3. 잃은 사람들을 먼저 lostMans에 체크한다.
4. 여분을 가진 사람들을 체크하면서 각 사람이 잃어버린 사람이라면, 잃어버리지 않았다고 체크하고, 체육복 입은 사람을 증가시킨다. 잃어버린 사람이 아니라면, 여분 체육복을 가진 사람으로 체크한다.
5. 여분을 가진 사람들을 좌, 우로 체크하며 빌려줄 수 있는지 확인한다.
- 시간복잡도 : N
```java
public int solution(int n, int[] lost, int[] reserve) {
int answer = n - lost.length;
boolean[] lostMans = new boolean[n+1];
boolean[] reserveMans = new boolean[n+1];
Arrays.sort(reserve);
for(int num : lost) lostMans[num] = true;
for(int num : reserve){
if(lostMans[num]){
lostMans[num] = false;
answer++;
}
else reserveMans[num] = true;
}
int[] dir = {-1, 1};
for(int num : reserve){
if(!reserveMans[num]) continue; …
```
> HanJaehee Programmers 42862 체육복

- HanJaehee/programmers/43105/README.md
- HanJaehee/programmers/43105/programmers43105.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43105)
1. 이전에는 상향식으로 구현해 이번엔 하향식으로 구현했다.
2. 정삼각형 형태를 직각 삼각형으로 변경해 계산했다.
3. 현재 인덱스가 arr[Y][x] 라면, arr[Y+1][x]에는 arr[Y+1][x] 와 arr[Y+1][x] + t[Y][x] 중 큰값을 넣고 arr[Y+1][x+1]에도 동일하게 적용해 가장 밑 층의 값들 중 최대값을 추출했다.
- 시간복잡도 : N^2
```java
public int solution(int[][] t) {
int len = t[t.length-1].length;
int[][] result = new int[len][len];
result[0][0] = t[0][0]; // 초기값 세팅
for(int i=0; i<len-1; ++i){
for(int j=0; j<t[i].length; ++j){
result[i+1][j] = Math.max(result[i][j] + t[i+1][j], result[i+1][j]);
result[i+1][j+1] = Math.max(result[i][j] + t[i+1][j+1], result[i+1][j+1]);
}
}
int max = -1;
for(int i=0; i<len; ++i){
max = Math.max(max, result[len-1][i]);
}
// print(result, len);
return max;
}
public void print(int[][] result, …
```
> HanJaehee Programmers 43105 정수 삼각형

- seunghwan/programmers/42898/P42898등굣길.java
- seunghwan/programmers/42898/README.md
- seunghwan/programmers/64063/P64063호텔방배정.java
- seunghwan/programmers/64063/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42898)
bfs를 이용한 경로탐색
1. 거리와 갯수가 중요, 최소 거리와 갯수를 저장할 map 생성
2. bfs 경로 탐색을 하며
2-1. 처음 방문 한 위치라면 최소거리를 min맵에 저장, 내 갯수를 cnt맵에 저장, que에 위치 넣기
2-2. 이미 방문 한 위치인데 저장된 거리가 내 거리보다 작다면 continue
2-3. 거리가 같다면 내 갯수만 cnt맵에 +
3. 모든 경로를 돌고나서 학교위치에 저장된 cnt를 return
- 시간복잡도
O(n^2) 맵 완탐
```java
import java.awt.*;
public class Solution {
public int solution(int m, int n, int[][] puddles) {
int [][] min = new int [n][m];
int [][] cnt = new int [n][m];
for(int [] i : puddles)
min[i[1]-1][i[0]-1] = -1;
cnt[0][0] = 1;
min[0][0] = 1;
Queue<Point> que = new LinkedList<>();
que.add(new Point(0,0));
int [] dr = {0,0,-1,1};
int [] dc = {1,-1,0,0};
int length = 1;
while(!que.isEmpty()){
int size = que.size(); …
```
> Ysh programmers 42898 등굣길

- juneyoung/programmers/42898/P42898등굣길.java
- juneyoung/programmers/42898/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42898)
1. 고려해야할 사항 
- m  x  n (100 x 100)
- 1,000,000,007로 나눈 나머지 리턴
- 오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로
2. 설계로직
1. dfs와 메모이제이션(dp배열)을 활용하여 해결
2. dp배열을 초기값인 -1로 세팅
3. 0,0 좌표에서 dfs탐색을 통해 **현재 위치의 dp배열의 값 +1 ( 현재의 길로 갈 수 있는 경우의 수)** 
1. 만약 현재 위치의 dp배열이 -1이 아니라면 **(이전에 왔던 길)** , 뒤로 돌아가면서 그 값 + 1로 dp배열 업데이트
3. 시간복잡도: O ( n x m ) 
```java
static int map[][] ,dp[][];
static final int div = 1000000007;
static int[] dr = { 1, 0 };
static int[] dc = { 0, 1 };
public int solution(int m, int n, int[][] puddles) {
map = new int[n][m];
dp = new int[n][m];
for(int i = 0; i < puddles.length; i++) 
map[puddles[i][1]-1][puddles[i][0]-1] = 1;
for(int i= 0; i < dp.length; i++) 
Arrays.fill(dp[i],-1);    
int …
```
> young programmers 42898 등굣길

- HanJaehee/programmers/49189/README.md
- HanJaehee/programmers/49189/programmers49189.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/49189)
1. BFS사용해서 탐색.
```java
List<Integer>[] list;
int[] result;
int max = 0;
public int solution(int n, int[][] edge) {
list = new ArrayList[n+1];
result = new int[n+1];
for(int i=1; i<=n; ++i){
list[i] = new ArrayList<>();
}
for(int[] line : edge){
list[line[0]].add(line[1]);
list[line[1]].add(line[0]);
}
bfs();
for(int i=1; i<=n; ++i){
if(max == result[i]) answer++;
System.out.println(result[i]);
}
return answer;
}
public void bfs(){
Queue<Point> q = new LinkedList<>();
q.add(new Point(1, 1));
result[1] = 1;
while(!q.isEmpty()){
Point p = q.poll();
max = Math.max(max, p.cnt);
for(int next : list[p.now]){
if(result[next] != 0) continue;
result[next] = p.cnt+1;
q.add(new …
```
> HanJaehee Programmers 49189 가장 먼 노드

- HanJaehee/programmers/49191/README.md
- HanJaehee/programmers/49191/programmers49191.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/49191)
1. 선수가 100명이하 이기 때문에 플루이드 와샬 사용.
- 시간복잡도 : N^3
```java
public int solution(int n, int[][] results) {
int INF = 100000;
int[][] map = new int[n+1][n+1];
for(int[] tmp : map){
Arrays.fill(tmp, INF);
}
for(int[] result : results){
map[result[0]][result[1]] = 1;
}
for(int k=1; k<=n; ++k){
for(int i=1; i<=n; ++i){
for(int j=1; j<=n; ++j){
if(map[i][j] > map[i][k] + map[k][j]){
map[i][j] = map[i][k] + map[k][j];
}
}
}
}
for(int i = 1; i < map.length; i++){
boolean flag = true;
for(int j = 1; j < map[i].length; j++) {
if(i == j) continue;
if(map[i][j] == INF && map[j][i] == INF) {
flag = false; break;
}
}
if(flag) answer++;
}
return answer;
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 …
> HanJaehee Programmers 49191 순위

- HanJaehee/programmers/43162/README.md
- HanJaehee/programmers/43162/programmers43162.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43162)
1. 각 컴퓨터마다 연결된 컴퓨터를 돌며 방문 체크를 한다.
2. 각 dfs 시작을 네트워크 하나로 간주하고, 카운트한다.
- 시간복잡도 : N^2
```java
boolean[] v;
public int solution(int n, int[][] computers) {
v = new boolean[n];
for(int i=0; i<n; ++i){
for(int j=0; j<n; ++j){
if(computers[i][j] == 1 && !v[i]){
dfs(computers, i, n);
answer++;
}
}
}
return answer;
}
public void dfs(int[][] computers, int idx, int n){
v[idx] = true;
for(int i=0; i<n; ++i){
if(computers[idx][i] == 1 && !v[i]) dfs(computers, i, n);
}
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 문제였습니다.
> HanJaehee Programmers 43162 네트워크

- HanJaehee/programmers/43164/README.md
- HanJaehee/programmers/43164/programmers43164.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43164)
1. 최대한 시작부터 걸러보려했지만, 결국 완탐에서 걸러내는 것으로 구현
2. ICN으로 시작하는 모든 지점을 통과하는 경로를 모두 찾아 그 중 알파벳 순으로 정렬해 첫번째 값을 리턴한다.
```java
List<String> answer = new ArrayList<>();
public String[] solution(String[][] tickets) {
dfs(tickets, 0, "ICN", "ICN", new boolean[tickets.length]);
Collections.sort(answer);
return answer.get(0).split(" ");
}
public void dfs(String[][] tickets, int idx, String now, String total, boolean[] visit){
if(idx == tickets.length){
answer.add(total);
return;
}
for(int i=0; i< tickets.length; ++i){
if(!visit[i] && tickets[i][0].equals(now)){
visit[i] = true;
dfs(tickets, idx+1, tickets[i][1], total + " " + tickets[i][1], visit);
visit[i] = false;
}
}
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 …
> HanJaehee Programmers 43164 여행 경로

- HanJaehee/programmers/43165/README.md
- HanJaehee/programmers/43165/programmers43165.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43165)
1. dfs를 활용, 각각 +,-를 케이스를 모두 탐색한다.
- 시간복잡도 : N^2
```java
public int solution(int[] numbers, int target) {
dfs(numbers, target, 0, 0);
return answer;
}
public void dfs(int[] numbers, int target, int idx, int sum){
if(idx == numbers.length){
if(sum == target) answer++;
return;
}
dfs(numbers, target, idx+1, sum + numbers[idx]);
dfs(numbers, target, idx+1, sum - numbers[idx]);
}
}
```
- 착실하게 문제의 요구사항을 따라가면 되는 문제였습니다.
> HanJaehee Programmers 43165 타겟 넘버

- HanJaehee/programmers/43163/README.md
- HanJaehee/programmers/43163/programmers43163.java
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43163)
1. dfs를 이용한 완탐을 이용해 구했다.
2. words를 다양하게 조합해 target과 일치할 때, 거쳐온 단어 개수의 최소값을 구했다.
- 시간복잡도 : N^2
```java
public class Solution {
int answer = Integer.MAX_VALUE;
boolean[] v;
public int solution(String begin, String target, String[] words) {
v = new boolean[words.length];
dfs(begin, target, words, 0);
if(answer == Integer.MAX_VALUE) return 0;
return answer;
}
public void dfs(String now, String target, String[] words, int count){
if(now.equals(target)){
answer = Math.min(answer, count);
return;
}
for(int i=0; i<words.length; ++i){
if(!v[i] && check(now, words[i])){
v[i] = true;
dfs(words[i], target, words, count+1);
v[i] = false;
}
}
}
public boolean check(String now, String target){
int count = 0;
for(int i=0; i<now.length(); …
```
> HanJaehee Programmers 43163 단어 변환

- HanJaehee/swexpert/2382/README.md
- HanJaehee/swexpert/2382/swexpert2382.java
[문제 링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV597vbqAH0DFAVl)
1. 리스트 내에 포지션에 대한 변수를 따로 만들어 관리한다.
2. 포지션 변수를 이용해 정렬해 처리했다.
```java
public class 미생물군집 {
static int[] dy = {0, -1, 1, 0, 0};
static int[] dx = {0, 0, 0, -1, 1};
static int N, M, K;
static List<Point> list = new ArrayList<>();
static class Point implements Comparable<Point> {
int pos, y, x, num, dir;
Point(int pos, int y, int x, int num, int dir) {
this.pos = pos;
this.y = y;
this.x = x;
this.dir = dir;
}
@Override
public int compareTo(Point o) {
if(this.pos == o.pos){
return o.num - this.num;
}
return this.pos - o.pos;
}
}
public static void main(String[] args) …
```
> HanJaehee SW Expert 2382 미생물 격리

- seunghwan/programmers/42897/P42897도둑질.java
- seunghwan/programmers/42897/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42897)
도둑을 도와서? 최대한 많은 돈을 훔치는 문제
2개의 인접한 집을 훔치면 경보가 울리게 된다.
집들이 동그랗게 연결이 되어있어 마지막 인덱스처리가 관건인 문제이다.
먼저 집이 1자로 그냥 연결 되어 있다고 생각하면 어렵지 않다.
현재 내 위치를 i라하면 i-2나 i-3 중 값이 더 큰 곳에서 넘어오면 된다.
식으로 보면
```
dp[i] = Math.max(dp[i-2],dp[i-3])+money[i];
```
그런데 마지막 집은 첫번째 집하고 함께 도둑질하지 못하니
첫번째 집을 훔쳤는지 안훔쳤는지가 중요해진다.
그래서 dp 2개를 만들어서
첫번째 집을 훔쳤을 때의 경우와
첫번째 집은 안훔쳤을 경우로 2개의 상황에 대해서 dp 계산을 하고
마지막 집을 계산할 때는 첫번째 집에서 안훔친 경우에서만 계산해주면 된다.
그 후 정답으로 나올 수 있는 후보는
0쓴 거에선 마지막에서 첫번째와 두번째 ( 첫번째와 두번째는 서로 영향을 못주니 둘 다 정답이 나올 수 있다.)
0 안 쓴 거에선 마지막과 마지막에서 첫번째 (위와 동일)
총 4개 중 가장 큰 값을 return 해주면 된다.
- 시간복잡도
O(N) 
```java
public class Solution {
public static void main(String[] args) {
System.out.println(solution(new int[] {1,2,3}));
}
static public int …
```
> Seunghwan programmers 42897 도둑질

- seunghwan/programmers/42895/P42895N으로표현.java
- seunghwan/programmers/42895/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42895)
N을 최소로 사용해서 number를 만드는 문제
가능한 사칙연산은 다 쓸 수 있고 ( +, -, *, / ) 추가로 숫자를 이어 붙이는게 가능하다 ex) 55
N을 한개씩 늘려가면서 모든 사칙연산을 다 해볼 수 있겠지만
그럴 경우 괄호 계산 때문에 경우의 수가 기하급수적으로 늘어난다.
ex) N = 5이고 4개를 쓴다고 하면
5 * 5 + 5 / 5 에서
5 * ( 5 + 5 ) / 5 의 경우도 신경 써줘야 한다.
이런 괄호 계산까지 마친 값들을 순차적으로 미리 저장 해 둔다면 훨씬 빠르게 해결이 가능해진다.
만약 N을 4개를 쓴다고 한다면 가능한 경우는
NNNN
N 1개 (사칙연산) N 3개
N 2개 (사칙연산) N 2개
N 3개 (사칙연산) N 1개
이렇게 4가지 밖에 없다.
값들을 저장해 놓을 땐 사칙연산 후 중복 되는 값이 있을 수 있으니 Set으로 중복제거 상태로 저장해둔다.
모든 계산을 마친 후에는 contains함수로 number가 나왔는지 확인하는데
HashSet을 사용하기 때문에 O(1)로 바로 확인이 가능하다.
8개까지 써보고 number를 구했으면 갯수 return
못 구했으면 -1 return 해주면 된다.
- 시간복잡도
O(8^2 * N^2) 
```java
import java.util.HashSet;
import java.util.Set;
public class P42895N으로표현 {
public int solution(int N, int number) { …
```
> Ysh programmers 42895 N으로표현

- juneyoung/programmers/43164/P43164여행경로.java
- juneyoung/programmers/43164/README.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/43164)
1. 고려해야할 사항 
- 주어진 공항 수 ( 10,000 이하 )
- tickets의 수는 알 수 없음.
- 만일 가능한 경로가 2개 이상일 경우 알파벳 순서가 앞서는 경로를 return 합니다.
2. 설계로직
1. 연결 리스트 생성 ( Map으로 구현 )
2. 연결리스트의 티켓 알파벳순 정렬
3. 깊이 우선 탐색 
1. 탈출 조건 : 티켓의 수보다 경로가 1개 더 많을 경우, 정답이 이미 구해졌을 경우 (처음 정답이 나오면 더 이상 탐색을 안해도 됨.)
2. 현재 위치에서 더 이상 갈 수 있는 곳이 없는 경우 , 이미 방문했을 경우 return 를 제외하고 모든 경로 탐색
3. 시간복잡도: O ( E x logN ) 
```java
Map<String, List<String>> map = new HashMap<>();
Map<String, boolean[]> visited = new HashMap<>();
boolean flag;
String ans;
public String[] solution(String[][] tickets) {
for(int i = 0; i < tickets.length; i++) {
String start = tickets[i][0];
String end = tickets[i][1];
map.merge(start,new …
```
> young programmers 43164 여행경로

- Vinjunho/programmers/1234/readme.md
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42577)
1. test
```python
test
```
- test
> rekalux programmers 1234 test

- HanJaehee/swexpert/2383/README.md
- HanJaehee/swexpert/2383/swea2383.java
[문제 링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5-BEE6AK0DFAVl&categoryId=AV5-BEE6AK0DFAVl&categoryType=CODE&problemTitle=%EC%A0%90%EC%8B%AC+%EC%8B%9D%EC%82%AC&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1)
1. 완전 탐색을 위해 dfs로 한 사람이 1번 계단, 2번 계단으로 가는 모든 경우에서 시뮬레이션
2. 시뮬레이션에서는 계단을 내려가는 경우를 먼저 처리함. 계단에서 나가는 것과 계단에 들어가는 것은 동시에 일어날 수 있는데, 들어가는 것을 먼저 처리하면 바로 나가진다. 따라서 편의상 나가는 것을 먼저 처리한다.
3. 사람 클래스에 각 계단 별 소요되는 시간과 계단에 들어가는 시간을 체크해 각 시간마다 이 사람이 계단에 들어갈 수 있는지, 나갈 시간이 되었는지를 체크한다.
4. 모든 사람이 계단을 나갔을 때의 시간을 리턴
5. 모든 케이스 중 최소값 구해 리턴
```java
public class 점심식사시간 {
static int N;
static int[][] map;
static class Person { …
```
> HanJaehee SWEA 2383 점심 식사 시간

- HanJaehee/swexpert/1953/README.md
- HanJaehee/swexpert/1953/swea1953.java
[문제 링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PpLlKAQ4DFAUq)
1. 거리 측정이 들어가야 해서 BFS로 측정
2. 각 구조물과 방향에 따른 조건이 가장 복잡했다.
```java
public class 탈주범검거 {
static int[][] map;
static int N, M, R, C, L;
static int[][] dy =
{
{4, 4, 4, 4}, // 상 하 좌 우
{-1, 1, 0, 0}, // 1, 상하좌우
{-1, 1, 4, 4}, // 2, 상하
{4, 4, 0, 0}, // 3, 좌우
{-1, 4, 4, 0}, // 4, 상우
{4, 1, 4, 0}, // 5, 하우
{4, 1, 0, 4}, // 6, 하좌
{-1, 4, 0, 4}, // 7, 상좌
};
static int[][] dx =
{
{4, 4, 4, 4}, // 상 하 좌 우
{0, 0, -1, 1},
{0, 0, 4, 4},
{4, 4, -1, 1},
{0, 4, 4, 1},
{4, 0, 4, 1},
{4, 0, -1, 4},
{0, 4, -1, 4},
};
static …
```
> HanJaehee SWEA 1953 탈주범 검거

- HanJaehee/swexpert/1949/README.md
- HanJaehee/swexpert/1949/swexpert1949.java
[문제 링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV597vbqAH0DFAVl)
1. DFS로 완전탐색
2. 탐색하며, 공사 유무를 갖고 다닌다.
3. 공사를 하지 않았을 때, 공사 가능하면 갈 수 있는 높이일 경우 공사 후 높이를 조정하고 탐색을 돈다.
4. 탐색 마친 후 원상태로 돌려놓는다.
```java
import java.util.List;
public class 등산로조성 {
static int N, K, MAX_BONG, MAX_ROUTE;
static int[][] map;
public static class Bong{
int y, x;
Bong(int y, int x){
this.y = y;
this.x = x;
}
}
static List<Bong> maxBongs = new ArrayList<>();
static int[] dy = {1,-1,0,0};
static int[] dx = {0,0,1,-1};
static boolean[][] visit;
BufferedReader br = new …
```
> HanJaehee SWEA 1949 등산로 조성

- seunghwan/SWEA/1953/P1953탈주범검거.java
- seunghwan/SWEA/1953/README.md
[문제 링크](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PpLlKAQ4DFAUq )
bfs의 아주 기본같은 문제
경과한 시간만큼 갈 수 있는 모든 길의 갯수,
즉 너비로 탐색했을 때 depth가 시간 이하인 길의 갯수를 구하면 된다.
다만 특이하게 각 터널의 모양에 따라 이동할 수 있는 길이 다르다는 것과
그 터널에서 이동하려는 곳에도 연결되는 터널이 있어야 이동이 가능하다는 것만 주의 하며 된다.
터널의 모양의 경우
먼저 상,하,좌,우 이동을 나타내는 dr[] , dc[] 를 만들고
각 터널의 번호에서 이동가능한 방향을 2차원배열에 미리 저장해주었다.
```java
static int dr[] = new int[] { -1, 1, 0, 0 };
static int dc[] = new int[] { 0, 0, -1, 1 }; // 상하좌우
static int tunnel[][] = new int[][] { {}, { 0, 1, 2, 3 }, { 0, 1 }, { 2, 3 }, { 0, 3 }, { 1, 3 }, { 1, 2 },{ 0, 2 } };
```
가려는 곳이 연결 되었는지는
가는 방향이 상이면 하 좌라면 우로 가는길을 가려는 곳이 가지고 있으면 된다.
상하는 0,1 좌우는 2,3 에 저장해 두었기 때문에
```java
int doYouHave = dir % 2 == 0 ? dir + 1 : dir - 1;
```
짝수면 +1 홀수면 -1로 필요한 방향을 쉽게 구할 수 있다.
가려고 하는 터널이 가진 …
> seunghwan swea 1953 탈주범 검거

- swanious/SWEA/2382/2382_미생물격리.js
- swanious/SWEA/2382/readme.md
> [문제 링크](https://swexpertacademy.com/main/learn/course/lectureProblemViewer.do)
1. 미생물이 동일한 위치로 움직이는 경우 처리
2. 벽에 닿는 경우(벽에 닿는 경우는 겹치지 않으므로 걍 Math.floor(미생물개수 / 2)해준다.)
시간복잡도: O(N\*M)
```javascript
const fs = require("fs");
const stdin = fs.readFileSync("test.txt").toString().split("\n");
const input = (() => {
let line = 0;
return () => stdin[line++];
})();
const DIR = { 1: [-1, 0], 2: [1, 0], 3: [0, -1], 4: [0, 1] };
const REVERSE = { 1: 2, 2: 1, 3: 4, 4: 3 };
const solution = (N, time, mapp) => {
// 시간이 0보다 클때 반복
while (time > 0) {
// 미생물 이동
const tempMap = new Map();
mapp.forEach((v) => {
let [y, x, vol, dir] = v;
const ny = y + DIR[dir][0];
const nx = x + DIR[dir][1];
if (ny === 0 || nx === 0 || ny === N - 1 || nx === N - 1) {
vol = Math.floor(vol / 2);
dir = REVERSE[dir];
} …
```
> swanious SWEA 2382 미생물 격리 js

- seunghwan/boj/2075/G5_2075N번째큰수.java
- seunghwan/boj/2075/README.md
[문제 링크](https://www.acmicpc.net/problem/2075)
pq활용
\1. 가장 마지막 row의 값들을 pq에 담기
\2. 내림차순으로 하나씩 꺼내기
\3. 꺼낸 수의 윗 값을 pq에 담기
\4. 2-3을 N번 수행 후 나온 값을 출력
- 시간복잡도
O(NlogN)
```java
package Gold;
public class G5_2075N번째큰수 {
static class node implements Comparable<node> {
int num;
int idx;
public node(int num, int idx) {
super();
this.idx = idx;
}
@Override
public int compareTo(node o) {
return Integer.compare(o.num, this.num);
}
}
StringTokenizer st; …
```
> Seunghwan boj 2075 N번째큰수

- seunghwan/boj/7662/G5_7662이중우선순위큐.java
- seunghwan/boj/7662/G5_7662이중우선순위큐_deque.java
- seunghwan/boj/7662/G5_7662이중우선순위큐_이진탐색트리.java
- seunghwan/boj/7662/README.md
[문제 링크](https://www.acmicpc.net/problem/7662)
프로그래머스에도 완전히 같은 문제가 있어 한번 풀어봤던 문제이다.
자료구조의 선택에 따라 3가지 방식으로 풀어보았다.
\----------------------------------------------------------
1. Deque 활용 (프로그래머스 통과, 백준 시간초과)
삭제 연산이 앞뒤로 일어나기 때문에
앞뒤로 입출력이 가능한 deque를 활용한 풀이이다.
출력시에는 앞뒤의 node만 꺼내면 되기 때문에 한번의 연산으로 가능하다.
다만 입력시 정렬 상태를 유지하기 위해 입력 때 마다 매번 sort를 수행하여 O(NlogN)을 수행하게 된다.
+) 지금 생각해보면 deque가 아닌 ArrayList를 이용한다면 데이터가 이미 정렬된 상태이므로 이진탐색을 통해 삽입 위치를 찾아 탐색 logN + Array 삽입 N 으로 조금 더 나았지 않을까 싶다.
\----------------------------------------------------------
2. Priority queue 2개 활용 (프로그래머스 ,백준 통과)
max heap과 min heap 2개의 자료구조를 이용한 풀이
인풋으로 들어오는 값을 max heap 과 min heap에 모두 넣어서
출력시 최댓값은 max heap, 최솟값은 min heap에서 삭제연산을 수행한다.
다만 하나의 데이터가 2개의 자료구조에 들어가기 때문에
max heap에선 삭제 되었지만 min heap에서는 존재하는 상태가 생기게 된다.
나는 이 부분을 해결하기 위해
삭제 …
> Seunghwan boj 7662 이중우선순위큐

- juneyoung/boj/7662/README.md
- juneyoung/boj/7662/boj7662.java
[문제 링크](https://www.acmicpc.net/problem/7662)
1. 고려해야할 사항 
- 연산의 개수 (1,000,000)  -> 선형 시간복잡도로 구현
2. 설계로직
1. 최대값과 최소값을 같이 다뤄야 하기 때문에 우선순위큐를 2개 사용 (minQueue, maxQueue)
2. 명령어가 'I' 이면 큐에 각각 add
3. 명령어가 'D'이면 이후에 들어오는 숫자값에 따라서 (min or max Queue에서 제거)
1. 해당 노드가 살아있는지 확인 후 살아있으면 큐에서 제거
4. 모든 명령을 다 수행하면 minQ or maxQ중 하나로 정답을 구함.
1. minQ나 maxQ나 결과가 동일하기 때문
2. 살아남은 숫자 필터링 후
3. Integer로 변환
4. 리스트로 변환
5. max = 결과 리스트의 마지막 인덱스 , min은 결과 리스트의 0번 인덱스
3. 시간복잡도: O ( N x logN ) 
```java
import java.io.*;
import java.util.stream.Collectors;
public class Main {
static int T, k;
static PriorityQueue<Point> maxQ = new PriorityQueue<>((o1, o2) -> o2.num - o1.num);
static PriorityQueue<Point> minQ = new PriorityQueue<>((o1, o2) -> o1.num - o2.num);
static class Point {
int num;
boolean …
```
> young boj  7662 이중우선순위큐

- Vinjunho/boj/7662/README.md
- Vinjunho/boj/7662/boj7662.java
- Vinjunho/boj/7662/boj7662.py
[문제 링크](https://www.acmicpc.net/problem/7662)
- ### java
1. 입력과 출력에 log(n) 을 원함
2. 정렬된 자료구조가 필요함
3. 중복을 제거해 줄 자료구조가 필요함
4. Treemap으로 한 번에 해결
5. I면 Treemap에 넣고 이미 존재하면 개수만 늘린다
6. D 1 이면 lastkey를 활용해 맨 오른쪽 노드 제거, D -1이면 firstkey를 활용해 맨 왼쪽 노드 제거(개수가 남아 있다면 개수만 1 줄임)
7. 비어있다면 Entry, 존재하면 lastkey, firstkey를 각각 출력한다
- n log(n)
- ### python
1. 입력과 출력에 log(n) 을 원함
2. 정렬된 자료구조가 필요함
3. 중복을 제거해 줄 자료구조가 필요함
4. 작은 수를 기준으로 하는 우선순위 큐, 큰 수를 기준으로 하는 우선순위 큐 이렇게 2개 만든다
5. I이면 두 큐에 모두 저장한다. 단, 인덱스 값을 넣어서 서로가 같은 수임을 인식시킨다
6. D 1 이면 내림차순 큐에서 제거, D -1이면 오름차순 큐에서 제거
7. 하나의 명령이 끝날 때마다 동시에 pop 값이 없는지 양쪽 큐를 확인한다. 있다면 최대한 pop한다.
8. 비어있다면 Entry, 존재하면 각 큐를 pop하여 출력한다
- n log(n)
- ### java
```python
import …
```
> Vinjunho boj 7662 이중우선순위큐

- HanJaehee/boj/7662/README.md
- HanJaehee/boj/7662/boj7662.java
[문제 링크](https://www.acmicpc.net/problem/7662)
1. TreeMap을 이용해 오름차순 정렬과 맨마지막, 맨처음 접근, 개수 카운트를 해결했다.
2. key는 우선순위를 의미하고, value는 해당 숫자가 들어간 개수를 의미해 중복된 숫자에 대한 연산을 줄여준다.
```java
public class 이중우선순위큐3 {
static TreeMap<Integer, Integer> treeMap = new TreeMap<>();
StringTokenizer st;
int T = Integer.parseInt(br.readLine());
for (int test = 1; test <= T; test++) {
int k = Integer.parseInt(br.readLine());
treeMap.clear();
for (int i = 0; i < k; i++) {
st = new StringTokenizer(br.readLine());
process(st.nextToken(), Integer.parseInt(st.nextToken()));
}
if …
```
> HanJaehee boj 7662 이중 우선순위 큐

- swanious/BOJ/21939/21939_문제추천시스템1.py
- swanious/BOJ/21939/readme.md
> [문제 링크](https://www.acmicpc.net/problem/21939)
1. max heap, min heap 생성하여 recommend에 따른 값 뽑기
2. 같은 난이도면 더 작은 문제번호가 나와야하므로 max heap의 경우 문제번호도 음수로 받기
```python
import sys
from heapq import heappop, heappush
from collections import defaultdict
input = sys.stdin.readline
N = int(input())
max_p = []
min_p = []
solved = defaultdict(bool)
for i in range(N):
p, l = map(int, input().split())
heappush(max_p, (-l, -p))
heappush(min_p, (l, p))
solved[p] = False
M = int(input())
for i in range(M):
temp = input().split()
cmd = temp[0]
rest = list(map(int, temp[1:]))
if cmd == 'add':
while solved[-max_p[0][1]]:
heappop(max_p)
while solved[min_p[0][1]]:
heappop(min_p)
solved[rest[0]] = False
heappush(max_p, (-rest[1], -rest[0]))
heappush(min_p, (rest[1], rest[0]))
elif cmd == 'solved':
solved[rest[0]] …
```
> swanious boj 21939 문제추천시스템 version 1

- seunghwan/boj/1068/G5_1068트리.java
- seunghwan/boj/1068/G5_1068트리_find.java
- seunghwan/boj/1068/README.md
[문제 링크](https://www.acmicpc.net/problem/1068)
- 2가지 방식으로 풀이하였음.
\* dfs를 이용해 루트부터 탐색하는 방식
1. 부모에 자식들을 저장하는 연결리스트 생성
2. 루트부터 dfs 탐색 시작
3. 제거된 노드를 만날경우 없는 노드로 치고 탐색 X
4. 탐색하며 자식이 0개인 노드를 만나면 answer++
5. answer 출력
- 시간 복잡도 : O(N)
\* union-find의 find를 이용하는 방식
1. 처음 입력을 받으며 부모로 선택되지 않은 노드를 체크 (단, 제거된 노드는 부모를 자기 자신으로 변경)
2. 부모로 한번도 선택되지 않은 노드는 리프노드 후보가 됨.
3. find 함수를 이용해 리프노드 후보들의 최상위 부모를 찾아감.
4. 최상위 부모는 루트노드이거나 제거된 노드 둘 중 하나.
5. 최상위 부모가 루트노드인 경우만 answer++
6. answer 출력
- 시간 복잡도 : find 시 경로 압축을 통해 O(N)
** 이 문제에서 유의할 점은 제거될 노드의 부모의 자식이 제거될 노드 하나뿐인 경우 그 부모노드는 리프노드가 된다는 것.
첫번째 풀이에선 제거된 노드를 없는 노드로 치는 것으로 위 경우가 해결이 가능하고
두번째 풀이에선 제거된 노드의 부모를 자기자신으로 바꾸는 것으로 해결 가능.
<details>
<summary>dfs 풀이</summary>
<div markdown="1">
```java
package Gold; …
```
> Seunghwan boj 1068 트리

- juneyoung/boj/6416/README.md
- juneyoung/boj/6416/boj6416.kt
[문제 링크](https://www.acmicpc.net/problem/6416)
1. 고려해야할 사항 
- root node가 1개
- 간선의 개수 == 노드 - 1
- 루트 노드를 제외한 모든 노드는 반드시 단 하나의 들어오는 간선이 존재한다.
2. 설계로직
1. 입력 받은 두 수가 (0,0), (-1,-1) 이 아닐 때 까지 map에 저장
- 부모 노드는 키(입력받은 수 ), 값(0) 계속 해서 증가
- 자식 노드는 키(입력받은 수 ), 값(1) 계속 해서 증가
2. 정상적으로 입력을 받았다면 count++ (간선의 갯수)
3. 트리인지 판별
1. map이 비어있을 경우
2. 간선의 수 == 노드 -1 && 맵의 값중 가장 큰 값이 2보다 작음(하나의 들어오는 간선만 존재), min값이 0 (루트노드), 값 0인 맵의 개수가 1 (루트노드가 1개) 일 경우
```kotlin
import java.util.*
fun main() = with(Scanner(System.`in`)) {
val map = mutableMapOf<Int, Int>()
var case = 1
var count = 0
while (true) {
val a = nextInt()
val b = nextInt()
count++
if (a == 0 && b == 0) {
if (
map.isEmpty() || (
count == map.size
&& map.values.maxOf { it } < 2
&& map.values.minOf { it } == 0
&& map.values.count { it == …
```
> young boj 6416 트리인가?

- myoung/boj/3197/boj3197.py
- myoung/programmers/42626/README.md
- myoung/programmers/42626/programmers_42626.py
[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/42626)
1. 주어진 scoville을 최소 힙으로 정렬합니다.
2. scoville 중 가장 작은 값이 K보다 작을 경우 
`섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)`
방법으로 새로운 음식을 생성하여 scoville에 추가합니다.
3. 섞을 수 없는 경우가 되면(남은 scoville의 요소 갯수가 2개보다 작을 때) `-1`을 반환합니다.
4. 가장 작은 원소가 K보다 크면 `answer`를 반환합니다.
- 시간복잡도: O(NlogN)
- heapq의 heapify 시간 복잡도: O(N)
- heapq의 heappop 시간 복잡도: O(logN)
- heapq의 heappush 시간 복잡도: O(logN)
- scoville의 요소 N개가 주어졌을 때, 섞을 수 있는 최대 횟수는 N-1
```python
import heapq
def solution(scoville, K):
answer = 0
heapq.heapify(scoville)
while len(scoville) > 1 and scoville[0] < K:
answer += 1
_first = heapq.heappop(scoville)
_second = heapq.heappop(scoville)
_new = _first + _second*2
heapq.heappush(scoville, _new)
if scoville[0] < K:
return -1 …
```
> myoung programmers 42626 더 맵게

- HanJaehee/boj/3584/README.md
- HanJaehee/boj/3584/boj3584.java
[문제 링크](https://www.acmicpc.net/problem/3584)
1. 배열을 자식 -> 부모 로 연결해주고 상향식으로 탐색. ex) tmp[son] = parent
2. 두 노드 중 첫번째 노드의 모든 부모를 set에 넣어준다.( 본인 포함, 두 노드가 부모, 자식 관계일 시 부모가 리턴됨 )
3. 두 번째 노드는 본인을 포함한 부모들이 set에 담겨있는지 확인하고, 담겨 있다면 그 수를 정답으로 리턴한다.
- 시간복잡도 : N
```java
public class 가장가까운공통조상 {
static int[][] tree;
StringTokenizer st;
int T = Integer.parseInt(br.readLine());
int N; // 노드의 수
for (int test = 1; test <= T; test++) {
N = Integer.parseInt(br.readLine());
tree = new int[N+1][1];
for (int i = 0; i < N - 1; i++) {
st = new …
```
> HanJaehee boj 3584 가장 가까운 공통 조상

- seunghwan/boj/9489/G4_9489사촌.java
- seunghwan/boj/9489/README.md
[문제 링크](https://www.acmicpc.net/problem/9489)
내 노드의 부모와 형제인 노드의 자식(사촌)의 갯수를 구하는 문제
일반적으론 내 노드와 부모의 부모가 같은 노드들의 갯수만 구하면 쉽게 풀이 가능하지만
좀 새롭게 풀어보고자 다른 방법으로 풀었다.
연속된 수의 갯수를 세서 ArrayList에 하나하나 담고
ArrayList의 내용만 보고 정답을 유추하는 방식으로 풀이했다.
그림으로 설명하면
위 그림에선 1,3,2,1,3 이 ArrayList에 들어간다.
여기서 보면 처음 1개가 루트이고
그 다음 인덱스인 3은 루트의 자식 갯수가 된다.
그 다음 인덱스 부터 3개인 2,1,3은 자식의 자식이고 서로 사촌관계가 된다.
여기서 찾는 값 15는 2,1,3중 1에 들어가 있었으니 1을 제외한 2 + 3이 사촌의 수가 된다.
위 방식으로 각각 사촌으로 묶이는 인덱스 범위를 뽑을 수 있고
그 범위 안에 찾는 값이 있으면 그 갯수를 제외한 사촌의 합을 구하면 정답을 구할 수 있다.
1. 연속된 수의 갯수를 세고 배열에 저장한다. 타겟인 수가 있으면 그 인덱스를 미리 저장
2. 큐에 루트부터 저장.
3. 큐에서 하나씩 꺼내서 거기 적혀있는 갯수만큼 다음 인덱스가 사촌지간
4. 인덱스를 들리며 큐에 그 값을 넣기
5. 타겟인 인덱스를 만나면 방금 사촌 범위였던 수의 합에서 타겟인덱스의 값을 뺀 수를 출력
- 시간복잡도
O(N)
```java
package Gold;
import …
```
> Seunghwan boj 9489 사촌

- seunghwan/boj/2250/G2_2250트리의높이와너비.java
- seunghwan/boj/2250/README.md
[문제 링크](https://www.acmicpc.net/problem/2250)
이 문제는 설명은 복잡하지만 이해하고 나면 굉장히 간단한 문제이다.
특징을 생각해보면
1. 열 하나에 하나의 노드만 들어간다.
2. 내 노드의 인덱스는 나의 왼쪽 노드가 다 완성된 후 다음 인덱스가 된다.
특징을 보면 왼쪽 -> 나 -> 오른쪽인 중위순회의 형태를 띄게 된다.
즉, 중위순회로 트리를 탐색 했을 때 나오는 순서대로 열 인덱스를 매긴 것이 된다.
행 인덱스는 깊이가 되니 탐색을 하며 각 깊이의 열 인덱스들을 저장해놓고
마지막에 각 깊이의 최소 인덱스와 최대 인덱스의 차이를 구해 가장 너비가 긴 길이와 깊이를 찾으면 된다.
- 시간복잡도
O(N)
```java
package Gold;
public class G2_2250트리의높이와너비 {
static class node {
int left;
int right;
}
static node nodeArr[];
static ArrayList<Integer> [] depthIdx;
static int idx = 1; …
```
> Seunghwan boj 2250 트리의 높이와 너비

- HanJaehee/boj/2250/README.md
- HanJaehee/boj/2250/boj2250.java
[문제 링크](https://www.acmicpc.net/problem/2250)
1. 1부터 N까지를 더한 후 자식으로 언급된 모든 노드번호를 제거한다. 그러면, 루트번호만 남게된다.
2. 트리를 중위순회로 탐색하며, 열(인덱스)와 레벨을 기록한다.
3. 기록할 때, 각 레벨에서 최소,최대 인덱스를 구한다.
4. 마지막에 각 레벨의 너비를 구하면서, 최대 너비와 넓이를 구한다.
- 시간복잡도 : N
```java
import java.util.List;
public class 트리의너비와높이 {
static class Node {
int num;
int level;
int idx;
Node left;
Node right;
Node(int num) {
}
}
static class Tree {
void inOrder(Node cur, int level) {
if (cur != null) {
if (cur.left != null) inOrder(cur.left, level + 1);
cur.idx = idx++;
cur.level = level;
min_idx[level] = Math.min(min_idx[level], cur.idx);
max_idx[level] = Math.max(max_idx[level], cur.idx);
if (cur.right != null) …
```
> HanJaehee boj 2250 트리의 높이와 너비

- HanJaehee/boj/13164/README.md
- HanJaehee/boj/13164/boj13164.java
[문제 링크](https://www.acmicpc.net/problem/13164)
1.  이미 정렬된 사람들을 입력받고, 인접한 두 사람의 키 차이를 배열에 저장하고 오름차순으로 정렬한다.
2.  정렬된 배열에서 N-K (N에서 K를 빼면 K개의 조합의 수이다) 개를 선택해 합하면, 답이나온다.
3.  [1,3,4]를 예로 [1,3] , [3,4] 인접한 두 그룹의 키 차이는 각각 2, 1이다.
4.  그리고 [1,3,4] 가 그룹일 때 키 차이는 3이다. 즉, 두 그룹의 차이의 합은 한 그룹이 되었을 때의 차이와 같다.
- 시간복잡도 : N
```java
public class 행복유치원 {
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
int K = Integer.parseInt(st.nextToken());
int[] mans = new …
```
> HanJaehee boj 13164 행복유치원

- seunghwan/boj/11000/G5_11000강의실배정.java
- seunghwan/boj/11000/README.md
[문제 링크](https://www.acmicpc.net/problem/11000)
1. 시작시간 끝시간 각각 다른 pq에 저장
2. 시작에서 하나씩 꺼내서 class갯수 증가
3. 꺼낸 시작시간과 같거나 작은 끝시간이 있으면 모두 poll 하고 class 개수 감소
4. 갯수 증가 할 때마다 max 확인
5. 시작시간 pq에서 다 꺼내면 더 이상 class가 증가할 일 없으니 종료
6. max 출력
- 시간복잡도
O(N)
```java
package Gold;
public class G5_11000강의실배정 {
PriorityQueue<Integer> start = new PriorityQueue<Integer>();
PriorityQueue<Integer> end = new PriorityQueue<Integer>();
for (int i = 0; i < N; i++) {
StringTokenizer st = new …
```
> Seunghwan boj 11000 강의실 배정

- seunghwan/boj/9084/G5_9084동전.java
- seunghwan/boj/9084/README.md
[문제 링크](https://www.acmicpc.net/problem/9084)
동전 갯수 구할 금액 : M
동전 종류 : N1, N2, ... NN
1. 1~M원까지 N1으로 만들수 있는 갯수 구해서 dp배열에 저장
2. 구할 때 dp[구할금액 - N1]에 구해진 갯수를 + 해주면 구하기 쉬움.
3. N1으로 만들어진 dp배열 위에 2번 방법으로 N2도 써서 구할 수 있는 갯수 구하기
4. NN까지 반복
5. dp[M] 출력
- 시간복잡도
O(NM)
```java
package Gold;
public class G5_9084동전 {
int T = Integer.parseInt(br.readLine());
for (int tc = 0; tc < T; tc++) {
br.readLine();
int[] arr = Arrays.stream(br.readLine().split(" ")).mapToInt(Integer::parseInt).toArray();
int money = Integer.parseInt(br.readLine());
int dp[] = new int[money + 1];
dp[0] = 1;
for …
```
> Seunghwan boj 9084 동전

- seunghwan/boj/5557/G5_5557a1학년.java
- seunghwan/boj/5557/README.md
[문제 링크](https://www.acmicpc.net/problem/5557)
등식의 갯수가 2^63-1개(long) 까지 가능하다고 한다.
완탐으론 불가능하고 dp를 이용해야 한다.
dp로 풀이하기 편하도록 하나의 장치가 있다.
상근이가 아는 숫자가 0부터 20까지 뿐이라 이 밖의 숫자가 중간 연산 중에 나오면 무시된다.는 조건이다.
연산에서 나올 수 있는 수를 20까지만 고려하면 되니 dp로 풀이가 가능한 것이다.
점화식으로
이번 숫자(arr[i])에 + - 를 해서 0~20을 만들 수 있는 경우의 수를 구하면된다.
dp 배열로 보면 아래와 같이 되고
​    0 1 2 .... 19 20
arr[0]
arr[1]
arr[2]
...
arr[N]
arr[0]의 경우 -를 넣으면 음수가 되니 arr[0]인 수 하나만 가능하고
그 다음 부터인 arr[1]부터는
dp[1] [0] = dp[0] [0 - arr[1]] + dp[0] [0 + arr[1]]
dp [1] [1] = dp[0] [1 - arr[1]] + dp[0] [1 + arr[1]]
...
dp[1] [20] = dp[0] [1-arr[20]] + dp[0] [1+arr[20]]
이런 식이 될 것이다.
예를 들어 이번 수가 3일 때
dp[i] [15]의 갯수는 12+3 = 15 , 18 - 3 = 15 이므로
이전 연산까지 만들어진 12와 18의 갯수를 더한 값이 되는 것이다.
설명이 조금 복잡한데 코드로 보면 간단하다.
- 시간복잡도
O(N) 
```java
package Gold; …
```
> Seunghwan boj 5557 1학년

- seunghwan/boj/2631/G5_2631줄세우기.java
- seunghwan/boj/2631/README.md
[문제 링크](https://www.acmicpc.net/problem/2631)
가장 적은 수의 이동으로 정렬 상태를 만드는 문제
가장 적은 수만 이동시켜 정렬을 시키기 위해선
가장 많이 정렬된 상태의 인원들을 찾아 그 이외의 사람들만 이동시키면 된다.
가장 많이 정렬된 상태? -> 가장 긴 정렬 상태? -> 최장 증가 수열 !
그렇다 LIS(Longest Incerasing Subsequence)를 구하는 문제였다.
LIS를 구하는 방법으로 내가 아는 것은 dp와 이분탐색이 있는데
N의 크기가 200밖에 되지 않으니 N^2으로 충분히 풀이가능하여 dp를 활용하였다.
LIS를 구한 뒤 자리를 옮기는 인원의 수를 구해야 하므로
전체인원에서 정렬된 인원의 수를 뺀 값을 출력하면 된다.
- 시간복잡도
O(N^2)
```java
package Gold;
public class G5_2631줄세우기 {
int arr[] = new int[N];
for (int i = 0; i < N; i++)
arr[i] = Integer.parseInt(br.readLine());
int dp[] = new …
```
> Seunghwan boj 2631 줄세우기

- seunghwan/boj/1715/G4_1715카드정렬하기.java
- seunghwan/boj/1715/README.md
[문제 링크](https://www.acmicpc.net/problem/1715)
현재 가지고 있는 카드뭉치 중 가장 작은 것 2개를 뽑아 새 뭉치를 만들면 최소의 비교로 가능하다.
여기서 현재 가지고 있는 카드뭉치는 새롭게 합쳐져 만들어진 뭉치까지 포함해서 작은 것 2개이다.
1. pq에 모든 카드 갯수 넣기
2. 작은 것 2개를 뽑아 비교횟수를 answer에 저장하고
3. 새로 만들어진 뭉치를 pq에 다시 넣기
4. 뭉치가 하나만 남을 때까지 돌고 answer 출력
- 시간복잡도
O(N)
```java
package Gold;
public class G4_1715카드정렬하기 {
PriorityQueue<Integer> pq = new PriorityQueue<Integer>();
for (int i = 0; i < N; i++)
pq.add(Integer.parseInt(br.readLine()));
while (pq.size() != 1) {
int cnt = pq.poll() + pq.poll(); …
```
> Seunghwan boj 1715 카드정렬하기

- seunghwan/boj/14567/G5_14567선수과목_dp.java
- seunghwan/boj/14567/G5_14567선수과목_위상.java
- seunghwan/boj/14567/README.md
[문제 링크](https://www.acmicpc.net/problem/14567)
일반적인 풀이는 위상정렬이고
추가로 선수 과목의 조건이 (1≤A<B≤N) 형태로 순차적이기 때문에 dp 풀이가 가능하다.
두가지 방법으로 모두 풀어보았다.
위상정렬 풀이
1. 부모 -> 자식 으로 연결리스트 생성
2. 연결리스트 생성하며 진입 차수(부모의 수) 저장
3. 진입 차수가 0인 노드 que에 저장
4. 한 뎁쓰가 한 학기가 되니 que의 size를 이용해 뎁쓰 표현
5. 하나 씩 꺼내서 answer[]에 학기 저장하고 자식들의 진입차수를 하나씩 빼기
6. 진입차수가 0이 된 자식은 que에 add
7. que가 비어지면 모든 answer 출력
dp 풀이
1. 자식 -> 부모로 연결리스트 생성
2. dp 배열 생성
3. 따로 조건을 안넣어주기 위해 모든 노드에 부모 0을 추가
4. 1부터 순서대로 노드의 부모들 중 가장 큰 수 +1을 dp에 저장
5. dp 출력
- 시간복잡도
O(N)
```java
package Gold;
public class G5_14567선수과목_위상 { …
```
> Seunghwan boj 14567 선수 과목

- HanJaehee/boj/9084/README.md
- HanJaehee/boj/9084/boj9084.java
[문제 링크](https://www.acmicpc.net/problem/9084)
1. C원 짜리 동전으로 M원을 만들 수 있는 가지 수를 배열로 만들었을 때, cache[M] = cache[M-C]가 성립한다.
2. 2원 짜리로 만들 수 있는 가지 수가 2원, 4원, 6원, 8원...이 같다.
3. 그리고 3원짜리로 6원을 만들 수 있는 가지수도 3원, 6원, 9원...이 같다.
4. 그럼 2원, 3원짜리로 6원을 만들 수 있는 가지수는 2원, 3원으로 각각 6원짜리까지 가지수를 구한 후 누적한다.
- 시간복잡도 : N
```java
public class 동전 {
StringTokenizer st;
int T = Integer.parseInt(br.readLine());
int[] coins, cache;
for (int test = 0; test < T; test++) {
//            coins = …
```
> HanJaehee boj 9084 동전

- HanJaehee/boj/12865/README.md
- HanJaehee/boj/12865/boj12865.java
[문제 링크](https://www.acmicpc.net/problem/12865)
1. Bottom-up 방식으로 각 무게에서 최대 가치를 누적해갔다.
- 시간복잡도 : N
```java
public class 평범한배낭 {
static int N, K;
static int dp[][], w[], v[];
StringTokenizer st = new StringTokenizer(br.readLine());
N = Integer.parseInt(st.nextToken());
K = Integer.parseInt(st.nextToken());
dp = new int[N + 1][K + 1];
w = new int[N + 1];
v = new int[N + 1];
for (int i = 1; i <= N; i++) {
st = new StringTokenizer(br.readLine());
w[i] = Integer.parseInt(st.nextToken());
v[i] = Integer.parseInt(st.nextToken());
}
for (int …
```
> HanJaehee boj 12865 평범한 배낭

- seunghwan/boj/1806/G4_1806부분합.java
- seunghwan/boj/1806/README.md
[문제 링크](https://www.acmicpc.net/problem/1806)
투포인터로 쉽게 풀이 가능
1. start end 0으로 두고 탐색시작
2. 합이 S넘어 갈 때까지 end >> 이동
3. S 넘어가면 갯수 min에 초기화 시키고 start>>이동 (sum에선 이전 수 뺄셈)
4. 2,3 반복 하다가 합이 S가 안넘는데 end가 끝에 도착하면 반복 종료
5. min 출력
- 시간복잡도
O(N)
```java
package Gold;
public class G4_1806부분합 {
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
int S = Integer.parseInt(st.nextToken());
int [] arr = new int [N];
st = new StringTokenizer(br.readLine());
for(int i = 0 ; i < N ; i++)
arr[i] = Integer.parseInt(st.nextToken());
int start …
```
> Seunghwan boj 1806 부분합

- juneyoung/programmers/92341/P92341주차요금계산.kt
- juneyoung/programmers/92341/README.md
[[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/92341)](https://programmers.co.kr/learn/courses/30/lessons/92341)
1. 고려해야할 사항 
- `⌈`a`⌉` : a보다 작지 않은 최소의 정수를 의미합니다. 즉, `올림`을 의미합니다.
- 완탐
2. 설계로직
1. 입/출차 기록 차량번호를 기준으로 그룹핑
2. 차량번호 오름차순 정렬
3. 각 차량번호를 기준으로 주차요금 계산
1. 시간 계산 (시간을 분으로 바꿔) 입차 / 출차 각각 sum
2. 출차 - 입차  = 누적 주차 시간 [ 단, 음수일 경우 + 1439 ( 23시59분 ) ] 
3. 누적 주차 시간을 기준으로 주차요금 계산
3. 시간복잡도: O (n x logn) 
```kotlin
import kotlin.math.ceil
fun solution(fees: IntArray, records: Array<String>): IntArray {
return records.map { it.split(' ') }
.groupBy { it[1] }
.asSequence()
.sortedBy { it.key.toInt() }
.map { it.value } 
.map { computeFee(computeTime(it), fees)  }
.toList()
.toIntArray()
}
fun computeFee(time: Int, fees: IntArray): Int {
var result = fees[1]
if (time > …
```
> young programmers 92341 주차요금계산

- myoung/boj/2250/README.md
- myoung/boj/2250/boj_2250.py
[문제 링크](https://www.acmicpc.net/problem/2250)
1. is_root라는 배열을 만들고 입력을 받으면서 자식 노드로 나온 노드들은 False 값으로 바꾼다. -> 배열을 이용해 root 찾음
2. 문제에서 나온 트리의 x축 순서는 중위순회 순서이므로 해당 순서를 column_idx에 저장한다. (key: x 좌표, val: 노드번호)
3. height_lst에 y축 기준으로 저장한다. (key: y축 값, val: 해당 행에 존재하는 노드 배열)
4. y축 기준으로 한 층 씩 너비를 확인하여 최대 너비와 해당 층 값을 구한다.
- 시간복잡도 : O(N)
```python
import sys
input = sys.stdin.readline
class Node:
def __init__(self, val, left, right):
self.val = val
self.left = left
self.right = right
tree = {}
N = int(input())
is_root = [True] * (1+N)
root = 0
for _ in range(N):
val, left, right = map(int, input().split())
node = Node(val, left, right)
tree[val] = node
if left >= 0:
is_root[left] = False
if right >= 0:
is_root[right] = False
for idx, val in enumerate(is_root):
if idx == 0:
continue
if val:
root = …
```
> myoung boj 2250 트리의 높이와 너비

- seunghwan/programmers/92343/P92343양과늑대.java
- seunghwan/programmers/92343/README.md
[[문제 링크](https://programmers.co.kr/learn/courses/30/lessons/92343)]
dfs를 이용한 완전탐색
단 각 상황에서 갈 수 있는 모든 길을 다음 장소 후보로 두어야 한다.
1. info 글로벌 변수로 옮기기
2. 관계리스트 만들기
3. dfs 실행
4. 현재 노드에 따라 양과 늑대 수 증가
5. 양과 늑대수가 같아지면 종료
6. 전 노드에서 받은 대기큐의 정보 내 큐에 옮기기
7. 현재 노드에서 갈 수 있는 노드 큐에 저장
8. 큐가 비어있으면 종료
9. 현재 큐 size만큼 돌면서 다음 노드로 dfs 실행
10. dfs돌고 나오면 방금 갔던 노드 다시 큐에 넣기
- 시간복잡도
O(N^2)
```java
public class P92343양과늑대 {
int[] ginfo;
ArrayList<Integer>[] list;
public int solution(int[] info, int[][] edges) {
int n = info.length;
ginfo = info;
list = new ArrayList[n];
for (int i = 0; i < n; i++)
list[i] = new ArrayList<Integer>();
for (int i[] : edges)
list[i[0]].add(i[1]);
dfs(0, 0, 0, new LinkedList<Integer>());
return answer;
}
public void …
```
> Seunghwan programmers 92343 양과늑대
